// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FullConfig represents the complete configuration structure
type FullConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Timeouts      *TimeoutsConfig        `protobuf:"bytes,2,opt,name=timeouts,proto3" json:"timeouts,omitempty"`
	Thresholds    *ThresholdsConfig      `protobuf:"bytes,3,opt,name=thresholds,proto3" json:"thresholds,omitempty"`
	Tasks         *TasksConfig           `protobuf:"bytes,4,opt,name=tasks,proto3" json:"tasks,omitempty"`
	Database      *DatabaseConfig        `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	Security      *SecurityConfig        `protobuf:"bytes,6,opt,name=security,proto3" json:"security,omitempty"`
	Logging       *LoggingConfig         `protobuf:"bytes,7,opt,name=logging,proto3" json:"logging,omitempty"`
	Tools         *ToolsConfig           `protobuf:"bytes,8,opt,name=tools,proto3" json:"tools,omitempty"`
	Workflow      *WorkflowConfig        `protobuf:"bytes,9,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Memory        *MemoryConfig          `protobuf:"bytes,10,opt,name=memory,proto3" json:"memory,omitempty"`
	Project       *ProjectConfig         `protobuf:"bytes,11,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullConfig) Reset() {
	*x = FullConfig{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullConfig) ProtoMessage() {}

func (x *FullConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullConfig.ProtoReflect.Descriptor instead.
func (*FullConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *FullConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FullConfig) GetTimeouts() *TimeoutsConfig {
	if x != nil {
		return x.Timeouts
	}
	return nil
}

func (x *FullConfig) GetThresholds() *ThresholdsConfig {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

func (x *FullConfig) GetTasks() *TasksConfig {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *FullConfig) GetDatabase() *DatabaseConfig {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *FullConfig) GetSecurity() *SecurityConfig {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *FullConfig) GetLogging() *LoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *FullConfig) GetTools() *ToolsConfig {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *FullConfig) GetWorkflow() *WorkflowConfig {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *FullConfig) GetMemory() *MemoryConfig {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *FullConfig) GetProject() *ProjectConfig {
	if x != nil {
		return x.Project
	}
	return nil
}

// TimeoutsConfig contains all timeout and duration settings
// Durations are stored as seconds (int64) for protobuf compatibility
type TimeoutsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task management timeouts (in seconds)
	TaskLockLease      int64 `protobuf:"varint,1,opt,name=task_lock_lease,json=taskLockLease,proto3" json:"task_lock_lease,omitempty"`
	TaskLockRenewal    int64 `protobuf:"varint,2,opt,name=task_lock_renewal,json=taskLockRenewal,proto3" json:"task_lock_renewal,omitempty"`
	StaleLockThreshold int64 `protobuf:"varint,3,opt,name=stale_lock_threshold,json=staleLockThreshold,proto3" json:"stale_lock_threshold,omitempty"`
	// Tool execution timeouts (in seconds)
	ToolDefault   int64 `protobuf:"varint,4,opt,name=tool_default,json=toolDefault,proto3" json:"tool_default,omitempty"`
	ToolScorecard int64 `protobuf:"varint,5,opt,name=tool_scorecard,json=toolScorecard,proto3" json:"tool_scorecard,omitempty"`
	ToolLinting   int64 `protobuf:"varint,6,opt,name=tool_linting,json=toolLinting,proto3" json:"tool_linting,omitempty"`
	ToolTesting   int64 `protobuf:"varint,7,opt,name=tool_testing,json=toolTesting,proto3" json:"tool_testing,omitempty"`
	ToolReport    int64 `protobuf:"varint,8,opt,name=tool_report,json=toolReport,proto3" json:"tool_report,omitempty"`
	// External services timeouts (in seconds)
	OllamaDownload int64 `protobuf:"varint,9,opt,name=ollama_download,json=ollamaDownload,proto3" json:"ollama_download,omitempty"`
	OllamaGenerate int64 `protobuf:"varint,10,opt,name=ollama_generate,json=ollamaGenerate,proto3" json:"ollama_generate,omitempty"`
	HttpClient     int64 `protobuf:"varint,11,opt,name=http_client,json=httpClient,proto3" json:"http_client,omitempty"`
	DatabaseRetry  int64 `protobuf:"varint,12,opt,name=database_retry,json=databaseRetry,proto3" json:"database_retry,omitempty"`
	// Context management timeouts (in seconds)
	ContextSummarize int64 `protobuf:"varint,13,opt,name=context_summarize,json=contextSummarize,proto3" json:"context_summarize,omitempty"`
	ContextBudget    int64 `protobuf:"varint,14,opt,name=context_budget,json=contextBudget,proto3" json:"context_budget,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TimeoutsConfig) Reset() {
	*x = TimeoutsConfig{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutsConfig) ProtoMessage() {}

func (x *TimeoutsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutsConfig.ProtoReflect.Descriptor instead.
func (*TimeoutsConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *TimeoutsConfig) GetTaskLockLease() int64 {
	if x != nil {
		return x.TaskLockLease
	}
	return 0
}

func (x *TimeoutsConfig) GetTaskLockRenewal() int64 {
	if x != nil {
		return x.TaskLockRenewal
	}
	return 0
}

func (x *TimeoutsConfig) GetStaleLockThreshold() int64 {
	if x != nil {
		return x.StaleLockThreshold
	}
	return 0
}

func (x *TimeoutsConfig) GetToolDefault() int64 {
	if x != nil {
		return x.ToolDefault
	}
	return 0
}

func (x *TimeoutsConfig) GetToolScorecard() int64 {
	if x != nil {
		return x.ToolScorecard
	}
	return 0
}

func (x *TimeoutsConfig) GetToolLinting() int64 {
	if x != nil {
		return x.ToolLinting
	}
	return 0
}

func (x *TimeoutsConfig) GetToolTesting() int64 {
	if x != nil {
		return x.ToolTesting
	}
	return 0
}

func (x *TimeoutsConfig) GetToolReport() int64 {
	if x != nil {
		return x.ToolReport
	}
	return 0
}

func (x *TimeoutsConfig) GetOllamaDownload() int64 {
	if x != nil {
		return x.OllamaDownload
	}
	return 0
}

func (x *TimeoutsConfig) GetOllamaGenerate() int64 {
	if x != nil {
		return x.OllamaGenerate
	}
	return 0
}

func (x *TimeoutsConfig) GetHttpClient() int64 {
	if x != nil {
		return x.HttpClient
	}
	return 0
}

func (x *TimeoutsConfig) GetDatabaseRetry() int64 {
	if x != nil {
		return x.DatabaseRetry
	}
	return 0
}

func (x *TimeoutsConfig) GetContextSummarize() int64 {
	if x != nil {
		return x.ContextSummarize
	}
	return 0
}

func (x *TimeoutsConfig) GetContextBudget() int64 {
	if x != nil {
		return x.ContextBudget
	}
	return 0
}

// ThresholdsConfig contains all threshold and limit settings
type ThresholdsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task analysis thresholds
	SimilarityThreshold  float64 `protobuf:"fixed64,1,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	MinDescriptionLength int32   `protobuf:"varint,2,opt,name=min_description_length,json=minDescriptionLength,proto3" json:"min_description_length,omitempty"`
	MinTaskConfidence    float64 `protobuf:"fixed64,3,opt,name=min_task_confidence,json=minTaskConfidence,proto3" json:"min_task_confidence,omitempty"`
	// Testing thresholds
	MinCoverage       int32   `protobuf:"varint,4,opt,name=min_coverage,json=minCoverage,proto3" json:"min_coverage,omitempty"`
	MinTestConfidence float64 `protobuf:"fixed64,5,opt,name=min_test_confidence,json=minTestConfidence,proto3" json:"min_test_confidence,omitempty"`
	// Estimation thresholds
	MinEstimationConfidence float64 `protobuf:"fixed64,6,opt,name=min_estimation_confidence,json=minEstimationConfidence,proto3" json:"min_estimation_confidence,omitempty"`
	MlxWeight               float64 `protobuf:"fixed64,7,opt,name=mlx_weight,json=mlxWeight,proto3" json:"mlx_weight,omitempty"`
	// Automation thresholds
	MaxParallelTasks        int32 `protobuf:"varint,8,opt,name=max_parallel_tasks,json=maxParallelTasks,proto3" json:"max_parallel_tasks,omitempty"`
	MaxTasksPerHost         int32 `protobuf:"varint,9,opt,name=max_tasks_per_host,json=maxTasksPerHost,proto3" json:"max_tasks_per_host,omitempty"`
	MaxAutomationIterations int32 `protobuf:"varint,10,opt,name=max_automation_iterations,json=maxAutomationIterations,proto3" json:"max_automation_iterations,omitempty"`
	MaxTasksPerWave         int32 `protobuf:"varint,18,opt,name=max_tasks_per_wave,json=maxTasksPerWave,proto3" json:"max_tasks_per_wave,omitempty"` // 0 = no limit; split waves so each has at most this many tasks
	// Context management thresholds
	TokensPerChar             float64 `protobuf:"fixed64,11,opt,name=tokens_per_char,json=tokensPerChar,proto3" json:"tokens_per_char,omitempty"`
	DefaultContextBudget      int32   `protobuf:"varint,12,opt,name=default_context_budget,json=defaultContextBudget,proto3" json:"default_context_budget,omitempty"`
	ContextReductionThreshold float64 `protobuf:"fixed64,13,opt,name=context_reduction_threshold,json=contextReductionThreshold,proto3" json:"context_reduction_threshold,omitempty"`
	// Security thresholds
	RateLimitRequests int32 `protobuf:"varint,14,opt,name=rate_limit_requests,json=rateLimitRequests,proto3" json:"rate_limit_requests,omitempty"`
	RateLimitWindow   int64 `protobuf:"varint,15,opt,name=rate_limit_window,json=rateLimitWindow,proto3" json:"rate_limit_window,omitempty"` // Duration in seconds
	MaxFileSize       int64 `protobuf:"varint,16,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"`
	MaxPathDepth      int32 `protobuf:"varint,17,opt,name=max_path_depth,json=maxPathDepth,proto3" json:"max_path_depth,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThresholdsConfig) Reset() {
	*x = ThresholdsConfig{}
	mi := &file_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdsConfig) ProtoMessage() {}

func (x *ThresholdsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdsConfig.ProtoReflect.Descriptor instead.
func (*ThresholdsConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *ThresholdsConfig) GetSimilarityThreshold() float64 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

func (x *ThresholdsConfig) GetMinDescriptionLength() int32 {
	if x != nil {
		return x.MinDescriptionLength
	}
	return 0
}

func (x *ThresholdsConfig) GetMinTaskConfidence() float64 {
	if x != nil {
		return x.MinTaskConfidence
	}
	return 0
}

func (x *ThresholdsConfig) GetMinCoverage() int32 {
	if x != nil {
		return x.MinCoverage
	}
	return 0
}

func (x *ThresholdsConfig) GetMinTestConfidence() float64 {
	if x != nil {
		return x.MinTestConfidence
	}
	return 0
}

func (x *ThresholdsConfig) GetMinEstimationConfidence() float64 {
	if x != nil {
		return x.MinEstimationConfidence
	}
	return 0
}

func (x *ThresholdsConfig) GetMlxWeight() float64 {
	if x != nil {
		return x.MlxWeight
	}
	return 0
}

func (x *ThresholdsConfig) GetMaxParallelTasks() int32 {
	if x != nil {
		return x.MaxParallelTasks
	}
	return 0
}

func (x *ThresholdsConfig) GetMaxTasksPerHost() int32 {
	if x != nil {
		return x.MaxTasksPerHost
	}
	return 0
}

func (x *ThresholdsConfig) GetMaxAutomationIterations() int32 {
	if x != nil {
		return x.MaxAutomationIterations
	}
	return 0
}

func (x *ThresholdsConfig) GetMaxTasksPerWave() int32 {
	if x != nil {
		return x.MaxTasksPerWave
	}
	return 0
}

func (x *ThresholdsConfig) GetTokensPerChar() float64 {
	if x != nil {
		return x.TokensPerChar
	}
	return 0
}

func (x *ThresholdsConfig) GetDefaultContextBudget() int32 {
	if x != nil {
		return x.DefaultContextBudget
	}
	return 0
}

func (x *ThresholdsConfig) GetContextReductionThreshold() float64 {
	if x != nil {
		return x.ContextReductionThreshold
	}
	return 0
}

func (x *ThresholdsConfig) GetRateLimitRequests() int32 {
	if x != nil {
		return x.RateLimitRequests
	}
	return 0
}

func (x *ThresholdsConfig) GetRateLimitWindow() int64 {
	if x != nil {
		return x.RateLimitWindow
	}
	return 0
}

func (x *ThresholdsConfig) GetMaxFileSize() int64 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *ThresholdsConfig) GetMaxPathDepth() int32 {
	if x != nil {
		return x.MaxPathDepth
	}
	return 0
}

// TasksConfig contains task management defaults and settings
type TasksConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Defaults
	DefaultStatus   string   `protobuf:"bytes,1,opt,name=default_status,json=defaultStatus,proto3" json:"default_status,omitempty"`
	DefaultPriority string   `protobuf:"bytes,2,opt,name=default_priority,json=defaultPriority,proto3" json:"default_priority,omitempty"`
	DefaultTags     []string `protobuf:"bytes,3,rep,name=default_tags,json=defaultTags,proto3" json:"default_tags,omitempty"`
	// Status workflow (map of status -> allowed next statuses)
	// Stored as JSON string for flexibility: {"Todo": ["In Progress"], ...}
	StatusWorkflowJson string `protobuf:"bytes,4,opt,name=status_workflow_json,json=statusWorkflowJson,proto3" json:"status_workflow_json,omitempty"`
	// Cleanup settings
	StaleThresholdHours int32 `protobuf:"varint,5,opt,name=stale_threshold_hours,json=staleThresholdHours,proto3" json:"stale_threshold_hours,omitempty"`
	AutoCleanupEnabled  bool  `protobuf:"varint,6,opt,name=auto_cleanup_enabled,json=autoCleanupEnabled,proto3" json:"auto_cleanup_enabled,omitempty"`
	CleanupDryRun       bool  `protobuf:"varint,7,opt,name=cleanup_dry_run,json=cleanupDryRun,proto3" json:"cleanup_dry_run,omitempty"`
	// Task ID settings
	IdFormat string `protobuf:"bytes,8,opt,name=id_format,json=idFormat,proto3" json:"id_format,omitempty"`
	IdPrefix string `protobuf:"bytes,9,opt,name=id_prefix,json=idPrefix,proto3" json:"id_prefix,omitempty"`
	// Clarity checks
	MinDescriptionLength int32 `protobuf:"varint,10,opt,name=min_description_length,json=minDescriptionLength,proto3" json:"min_description_length,omitempty"`
	RequireDescription   bool  `protobuf:"varint,11,opt,name=require_description,json=requireDescription,proto3" json:"require_description,omitempty"`
	AutoClarify          bool  `protobuf:"varint,12,opt,name=auto_clarify,json=autoClarify,proto3" json:"auto_clarify,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TasksConfig) Reset() {
	*x = TasksConfig{}
	mi := &file_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksConfig) ProtoMessage() {}

func (x *TasksConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksConfig.ProtoReflect.Descriptor instead.
func (*TasksConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *TasksConfig) GetDefaultStatus() string {
	if x != nil {
		return x.DefaultStatus
	}
	return ""
}

func (x *TasksConfig) GetDefaultPriority() string {
	if x != nil {
		return x.DefaultPriority
	}
	return ""
}

func (x *TasksConfig) GetDefaultTags() []string {
	if x != nil {
		return x.DefaultTags
	}
	return nil
}

func (x *TasksConfig) GetStatusWorkflowJson() string {
	if x != nil {
		return x.StatusWorkflowJson
	}
	return ""
}

func (x *TasksConfig) GetStaleThresholdHours() int32 {
	if x != nil {
		return x.StaleThresholdHours
	}
	return 0
}

func (x *TasksConfig) GetAutoCleanupEnabled() bool {
	if x != nil {
		return x.AutoCleanupEnabled
	}
	return false
}

func (x *TasksConfig) GetCleanupDryRun() bool {
	if x != nil {
		return x.CleanupDryRun
	}
	return false
}

func (x *TasksConfig) GetIdFormat() string {
	if x != nil {
		return x.IdFormat
	}
	return ""
}

func (x *TasksConfig) GetIdPrefix() string {
	if x != nil {
		return x.IdPrefix
	}
	return ""
}

func (x *TasksConfig) GetMinDescriptionLength() int32 {
	if x != nil {
		return x.MinDescriptionLength
	}
	return 0
}

func (x *TasksConfig) GetRequireDescription() bool {
	if x != nil {
		return x.RequireDescription
	}
	return false
}

func (x *TasksConfig) GetAutoClarify() bool {
	if x != nil {
		return x.AutoClarify
	}
	return false
}

// DatabaseConfig contains database settings
type DatabaseConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SqlitePath          string                 `protobuf:"bytes,1,opt,name=sqlite_path,json=sqlitePath,proto3" json:"sqlite_path,omitempty"`
	JsonFallbackPath    string                 `protobuf:"bytes,2,opt,name=json_fallback_path,json=jsonFallbackPath,proto3" json:"json_fallback_path,omitempty"`
	BackupPath          string                 `protobuf:"bytes,3,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	MaxConnections      int32                  `protobuf:"varint,4,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	ConnectionTimeout   int64                  `protobuf:"varint,5,opt,name=connection_timeout,json=connectionTimeout,proto3" json:"connection_timeout,omitempty"` // Duration in seconds
	QueryTimeout        int64                  `protobuf:"varint,6,opt,name=query_timeout,json=queryTimeout,proto3" json:"query_timeout,omitempty"`                // Duration in seconds
	RetryAttempts       int32                  `protobuf:"varint,7,opt,name=retry_attempts,json=retryAttempts,proto3" json:"retry_attempts,omitempty"`
	RetryInitialDelay   int64                  `protobuf:"varint,8,opt,name=retry_initial_delay,json=retryInitialDelay,proto3" json:"retry_initial_delay,omitempty"` // Duration in seconds
	RetryMaxDelay       int64                  `protobuf:"varint,9,opt,name=retry_max_delay,json=retryMaxDelay,proto3" json:"retry_max_delay,omitempty"`             // Duration in seconds
	RetryMultiplier     float64                `protobuf:"fixed64,10,opt,name=retry_multiplier,json=retryMultiplier,proto3" json:"retry_multiplier,omitempty"`
	AutoVacuum          bool                   `protobuf:"varint,11,opt,name=auto_vacuum,json=autoVacuum,proto3" json:"auto_vacuum,omitempty"`
	WalMode             bool                   `protobuf:"varint,12,opt,name=wal_mode,json=walMode,proto3" json:"wal_mode,omitempty"`
	CheckpointInterval  int32                  `protobuf:"varint,13,opt,name=checkpoint_interval,json=checkpointInterval,proto3" json:"checkpoint_interval,omitempty"`
	BackupRetentionDays int32                  `protobuf:"varint,14,opt,name=backup_retention_days,json=backupRetentionDays,proto3" json:"backup_retention_days,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DatabaseConfig) Reset() {
	*x = DatabaseConfig{}
	mi := &file_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseConfig) ProtoMessage() {}

func (x *DatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseConfig.ProtoReflect.Descriptor instead.
func (*DatabaseConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *DatabaseConfig) GetSqlitePath() string {
	if x != nil {
		return x.SqlitePath
	}
	return ""
}

func (x *DatabaseConfig) GetJsonFallbackPath() string {
	if x != nil {
		return x.JsonFallbackPath
	}
	return ""
}

func (x *DatabaseConfig) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *DatabaseConfig) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *DatabaseConfig) GetConnectionTimeout() int64 {
	if x != nil {
		return x.ConnectionTimeout
	}
	return 0
}

func (x *DatabaseConfig) GetQueryTimeout() int64 {
	if x != nil {
		return x.QueryTimeout
	}
	return 0
}

func (x *DatabaseConfig) GetRetryAttempts() int32 {
	if x != nil {
		return x.RetryAttempts
	}
	return 0
}

func (x *DatabaseConfig) GetRetryInitialDelay() int64 {
	if x != nil {
		return x.RetryInitialDelay
	}
	return 0
}

func (x *DatabaseConfig) GetRetryMaxDelay() int64 {
	if x != nil {
		return x.RetryMaxDelay
	}
	return 0
}

func (x *DatabaseConfig) GetRetryMultiplier() float64 {
	if x != nil {
		return x.RetryMultiplier
	}
	return 0
}

func (x *DatabaseConfig) GetAutoVacuum() bool {
	if x != nil {
		return x.AutoVacuum
	}
	return false
}

func (x *DatabaseConfig) GetWalMode() bool {
	if x != nil {
		return x.WalMode
	}
	return false
}

func (x *DatabaseConfig) GetCheckpointInterval() int32 {
	if x != nil {
		return x.CheckpointInterval
	}
	return 0
}

func (x *DatabaseConfig) GetBackupRetentionDays() int32 {
	if x != nil {
		return x.BackupRetentionDays
	}
	return 0
}

// SecurityConfig contains security settings
type SecurityConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RateLimit      *RateLimitConfig       `protobuf:"bytes,1,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	PathValidation *PathValidationConfig  `protobuf:"bytes,2,opt,name=path_validation,json=pathValidation,proto3" json:"path_validation,omitempty"`
	FileLimits     *FileLimitsConfig      `protobuf:"bytes,3,opt,name=file_limits,json=fileLimits,proto3" json:"file_limits,omitempty"`
	AccessControl  *AccessControlConfig   `protobuf:"bytes,4,opt,name=access_control,json=accessControl,proto3" json:"access_control,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SecurityConfig) Reset() {
	*x = SecurityConfig{}
	mi := &file_proto_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfig) ProtoMessage() {}

func (x *SecurityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfig.ProtoReflect.Descriptor instead.
func (*SecurityConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *SecurityConfig) GetRateLimit() *RateLimitConfig {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *SecurityConfig) GetPathValidation() *PathValidationConfig {
	if x != nil {
		return x.PathValidation
	}
	return nil
}

func (x *SecurityConfig) GetFileLimits() *FileLimitsConfig {
	if x != nil {
		return x.FileLimits
	}
	return nil
}

func (x *SecurityConfig) GetAccessControl() *AccessControlConfig {
	if x != nil {
		return x.AccessControl
	}
	return nil
}

// RateLimitConfig contains rate limiting settings
type RateLimitConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RequestsPerWindow int32                  `protobuf:"varint,2,opt,name=requests_per_window,json=requestsPerWindow,proto3" json:"requests_per_window,omitempty"`
	WindowDuration    int64                  `protobuf:"varint,3,opt,name=window_duration,json=windowDuration,proto3" json:"window_duration,omitempty"` // Duration in seconds
	BurstSize         int32                  `protobuf:"varint,4,opt,name=burst_size,json=burstSize,proto3" json:"burst_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimitConfig) Reset() {
	*x = RateLimitConfig{}
	mi := &file_proto_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitConfig) ProtoMessage() {}

func (x *RateLimitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitConfig.ProtoReflect.Descriptor instead.
func (*RateLimitConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{6}
}

func (x *RateLimitConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RateLimitConfig) GetRequestsPerWindow() int32 {
	if x != nil {
		return x.RequestsPerWindow
	}
	return 0
}

func (x *RateLimitConfig) GetWindowDuration() int64 {
	if x != nil {
		return x.WindowDuration
	}
	return 0
}

func (x *RateLimitConfig) GetBurstSize() int32 {
	if x != nil {
		return x.BurstSize
	}
	return 0
}

// PathValidationConfig contains path validation settings
type PathValidationConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AllowAbsolutePaths bool                   `protobuf:"varint,2,opt,name=allow_absolute_paths,json=allowAbsolutePaths,proto3" json:"allow_absolute_paths,omitempty"`
	MaxDepth           int32                  `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	BlockedPatterns    []string               `protobuf:"bytes,4,rep,name=blocked_patterns,json=blockedPatterns,proto3" json:"blocked_patterns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PathValidationConfig) Reset() {
	*x = PathValidationConfig{}
	mi := &file_proto_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathValidationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathValidationConfig) ProtoMessage() {}

func (x *PathValidationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathValidationConfig.ProtoReflect.Descriptor instead.
func (*PathValidationConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{7}
}

func (x *PathValidationConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PathValidationConfig) GetAllowAbsolutePaths() bool {
	if x != nil {
		return x.AllowAbsolutePaths
	}
	return false
}

func (x *PathValidationConfig) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *PathValidationConfig) GetBlockedPatterns() []string {
	if x != nil {
		return x.BlockedPatterns
	}
	return nil
}

// FileLimitsConfig contains file operation limits
type FileLimitsConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxFileSize          int64                  `protobuf:"varint,1,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"`
	MaxFilesPerOperation int32                  `protobuf:"varint,2,opt,name=max_files_per_operation,json=maxFilesPerOperation,proto3" json:"max_files_per_operation,omitempty"`
	AllowedExtensions    []string               `protobuf:"bytes,3,rep,name=allowed_extensions,json=allowedExtensions,proto3" json:"allowed_extensions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FileLimitsConfig) Reset() {
	*x = FileLimitsConfig{}
	mi := &file_proto_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLimitsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLimitsConfig) ProtoMessage() {}

func (x *FileLimitsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLimitsConfig.ProtoReflect.Descriptor instead.
func (*FileLimitsConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{8}
}

func (x *FileLimitsConfig) GetMaxFileSize() int64 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *FileLimitsConfig) GetMaxFilesPerOperation() int32 {
	if x != nil {
		return x.MaxFilesPerOperation
	}
	return 0
}

func (x *FileLimitsConfig) GetAllowedExtensions() []string {
	if x != nil {
		return x.AllowedExtensions
	}
	return nil
}

// AccessControlConfig contains access control settings
type AccessControlConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DefaultPolicy   string                 `protobuf:"bytes,2,opt,name=default_policy,json=defaultPolicy,proto3" json:"default_policy,omitempty"` // "allow" or "deny"
	RestrictedTools []string               `protobuf:"bytes,3,rep,name=restricted_tools,json=restrictedTools,proto3" json:"restricted_tools,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessControlConfig) Reset() {
	*x = AccessControlConfig{}
	mi := &file_proto_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessControlConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessControlConfig) ProtoMessage() {}

func (x *AccessControlConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessControlConfig.ProtoReflect.Descriptor instead.
func (*AccessControlConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{9}
}

func (x *AccessControlConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AccessControlConfig) GetDefaultPolicy() string {
	if x != nil {
		return x.DefaultPolicy
	}
	return ""
}

func (x *AccessControlConfig) GetRestrictedTools() []string {
	if x != nil {
		return x.RestrictedTools
	}
	return nil
}

// LoggingConfig contains logging settings
type LoggingConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Level             string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	ToolLevel         string                 `protobuf:"bytes,2,opt,name=tool_level,json=toolLevel,proto3" json:"tool_level,omitempty"`
	FrameworkLevel    string                 `protobuf:"bytes,3,opt,name=framework_level,json=frameworkLevel,proto3" json:"framework_level,omitempty"`
	Format            string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	IncludeTimestamps bool                   `protobuf:"varint,5,opt,name=include_timestamps,json=includeTimestamps,proto3" json:"include_timestamps,omitempty"`
	IncludeCaller     bool                   `protobuf:"varint,6,opt,name=include_caller,json=includeCaller,proto3" json:"include_caller,omitempty"`
	ColorOutput       bool                   `protobuf:"varint,7,opt,name=color_output,json=colorOutput,proto3" json:"color_output,omitempty"`
	LogDir            string                 `protobuf:"bytes,8,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	LogFile           string                 `protobuf:"bytes,9,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	SessionLogDir     string                 `protobuf:"bytes,10,opt,name=session_log_dir,json=sessionLogDir,proto3" json:"session_log_dir,omitempty"`
	LogRotation       *LogRotationConfig     `protobuf:"bytes,11,opt,name=log_rotation,json=logRotation,proto3" json:"log_rotation,omitempty"`
	RetentionDays     int32                  `protobuf:"varint,12,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	AutoCleanup       bool                   `protobuf:"varint,13,opt,name=auto_cleanup,json=autoCleanup,proto3" json:"auto_cleanup,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoggingConfig) Reset() {
	*x = LoggingConfig{}
	mi := &file_proto_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingConfig) ProtoMessage() {}

func (x *LoggingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingConfig.ProtoReflect.Descriptor instead.
func (*LoggingConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{10}
}

func (x *LoggingConfig) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LoggingConfig) GetToolLevel() string {
	if x != nil {
		return x.ToolLevel
	}
	return ""
}

func (x *LoggingConfig) GetFrameworkLevel() string {
	if x != nil {
		return x.FrameworkLevel
	}
	return ""
}

func (x *LoggingConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *LoggingConfig) GetIncludeTimestamps() bool {
	if x != nil {
		return x.IncludeTimestamps
	}
	return false
}

func (x *LoggingConfig) GetIncludeCaller() bool {
	if x != nil {
		return x.IncludeCaller
	}
	return false
}

func (x *LoggingConfig) GetColorOutput() bool {
	if x != nil {
		return x.ColorOutput
	}
	return false
}

func (x *LoggingConfig) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *LoggingConfig) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *LoggingConfig) GetSessionLogDir() string {
	if x != nil {
		return x.SessionLogDir
	}
	return ""
}

func (x *LoggingConfig) GetLogRotation() *LogRotationConfig {
	if x != nil {
		return x.LogRotation
	}
	return nil
}

func (x *LoggingConfig) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *LoggingConfig) GetAutoCleanup() bool {
	if x != nil {
		return x.AutoCleanup
	}
	return false
}

// LogRotationConfig contains log rotation settings
type LogRotationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MaxSize       int64                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxFiles      int32                  `protobuf:"varint,3,opt,name=max_files,json=maxFiles,proto3" json:"max_files,omitempty"`
	Compress      bool                   `protobuf:"varint,4,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRotationConfig) Reset() {
	*x = LogRotationConfig{}
	mi := &file_proto_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRotationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRotationConfig) ProtoMessage() {}

func (x *LogRotationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRotationConfig.ProtoReflect.Descriptor instead.
func (*LogRotationConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{11}
}

func (x *LogRotationConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LogRotationConfig) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *LogRotationConfig) GetMaxFiles() int32 {
	if x != nil {
		return x.MaxFiles
	}
	return 0
}

func (x *LogRotationConfig) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

// ToolsConfig contains tool-specific settings
type ToolsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scorecard     *ScorecardConfig       `protobuf:"bytes,1,opt,name=scorecard,proto3" json:"scorecard,omitempty"`
	Report        *ReportConfig          `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	Linting       *LintingConfig         `protobuf:"bytes,3,opt,name=linting,proto3" json:"linting,omitempty"`
	Testing       *TestingConfig         `protobuf:"bytes,4,opt,name=testing,proto3" json:"testing,omitempty"`
	Mlx           *MLXConfig             `protobuf:"bytes,5,opt,name=mlx,proto3" json:"mlx,omitempty"`
	Ollama        *OllamaConfig          `protobuf:"bytes,6,opt,name=ollama,proto3" json:"ollama,omitempty"`
	Context       *ContextConfig         `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsConfig) Reset() {
	*x = ToolsConfig{}
	mi := &file_proto_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsConfig) ProtoMessage() {}

func (x *ToolsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsConfig.ProtoReflect.Descriptor instead.
func (*ToolsConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{12}
}

func (x *ToolsConfig) GetScorecard() *ScorecardConfig {
	if x != nil {
		return x.Scorecard
	}
	return nil
}

func (x *ToolsConfig) GetReport() *ReportConfig {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ToolsConfig) GetLinting() *LintingConfig {
	if x != nil {
		return x.Linting
	}
	return nil
}

func (x *ToolsConfig) GetTesting() *TestingConfig {
	if x != nil {
		return x.Testing
	}
	return nil
}

func (x *ToolsConfig) GetMlx() *MLXConfig {
	if x != nil {
		return x.Mlx
	}
	return nil
}

func (x *ToolsConfig) GetOllama() *OllamaConfig {
	if x != nil {
		return x.Ollama
	}
	return nil
}

func (x *ToolsConfig) GetContext() *ContextConfig {
	if x != nil {
		return x.Context
	}
	return nil
}

// ScorecardConfig contains scorecard tool settings
type ScorecardConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default scores as JSON string: {"security": 50, "testing": 50, ...}
	DefaultScoresJson string `protobuf:"bytes,1,opt,name=default_scores_json,json=defaultScoresJson,proto3" json:"default_scores_json,omitempty"`
	IncludeWisdom     bool   `protobuf:"varint,2,opt,name=include_wisdom,json=includeWisdom,proto3" json:"include_wisdom,omitempty"`
	OutputFormat      string `protobuf:"bytes,3,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScorecardConfig) Reset() {
	*x = ScorecardConfig{}
	mi := &file_proto_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScorecardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScorecardConfig) ProtoMessage() {}

func (x *ScorecardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScorecardConfig.ProtoReflect.Descriptor instead.
func (*ScorecardConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{13}
}

func (x *ScorecardConfig) GetDefaultScoresJson() string {
	if x != nil {
		return x.DefaultScoresJson
	}
	return ""
}

func (x *ScorecardConfig) GetIncludeWisdom() bool {
	if x != nil {
		return x.IncludeWisdom
	}
	return false
}

func (x *ScorecardConfig) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

// ReportConfig contains report tool settings
type ReportConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DefaultFormat          string                 `protobuf:"bytes,1,opt,name=default_format,json=defaultFormat,proto3" json:"default_format,omitempty"`
	DefaultOutputPath      string                 `protobuf:"bytes,2,opt,name=default_output_path,json=defaultOutputPath,proto3" json:"default_output_path,omitempty"`
	IncludeMetrics         bool                   `protobuf:"varint,3,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	IncludeRecommendations bool                   `protobuf:"varint,4,opt,name=include_recommendations,json=includeRecommendations,proto3" json:"include_recommendations,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReportConfig) Reset() {
	*x = ReportConfig{}
	mi := &file_proto_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportConfig) ProtoMessage() {}

func (x *ReportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportConfig.ProtoReflect.Descriptor instead.
func (*ReportConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{14}
}

func (x *ReportConfig) GetDefaultFormat() string {
	if x != nil {
		return x.DefaultFormat
	}
	return ""
}

func (x *ReportConfig) GetDefaultOutputPath() string {
	if x != nil {
		return x.DefaultOutputPath
	}
	return ""
}

func (x *ReportConfig) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

func (x *ReportConfig) GetIncludeRecommendations() bool {
	if x != nil {
		return x.IncludeRecommendations
	}
	return false
}

// LintingConfig contains linting tool settings
type LintingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultLinter string                 `protobuf:"bytes,1,opt,name=default_linter,json=defaultLinter,proto3" json:"default_linter,omitempty"`
	AutoFix       bool                   `protobuf:"varint,2,opt,name=auto_fix,json=autoFix,proto3" json:"auto_fix,omitempty"`
	IncludeHints  bool                   `protobuf:"varint,3,opt,name=include_hints,json=includeHints,proto3" json:"include_hints,omitempty"`
	Timeout       int64                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // Duration in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintingConfig) Reset() {
	*x = LintingConfig{}
	mi := &file_proto_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintingConfig) ProtoMessage() {}

func (x *LintingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintingConfig.ProtoReflect.Descriptor instead.
func (*LintingConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{15}
}

func (x *LintingConfig) GetDefaultLinter() string {
	if x != nil {
		return x.DefaultLinter
	}
	return ""
}

func (x *LintingConfig) GetAutoFix() bool {
	if x != nil {
		return x.AutoFix
	}
	return false
}

func (x *LintingConfig) GetIncludeHints() bool {
	if x != nil {
		return x.IncludeHints
	}
	return false
}

func (x *LintingConfig) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// TestingConfig contains testing tool settings
type TestingConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DefaultFramework string                 `protobuf:"bytes,1,opt,name=default_framework,json=defaultFramework,proto3" json:"default_framework,omitempty"`
	MinCoverage      int32                  `protobuf:"varint,2,opt,name=min_coverage,json=minCoverage,proto3" json:"min_coverage,omitempty"`
	CoverageFormat   string                 `protobuf:"bytes,3,opt,name=coverage_format,json=coverageFormat,proto3" json:"coverage_format,omitempty"`
	Verbose          bool                   `protobuf:"varint,4,opt,name=verbose,proto3" json:"verbose,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TestingConfig) Reset() {
	*x = TestingConfig{}
	mi := &file_proto_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingConfig) ProtoMessage() {}

func (x *TestingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingConfig.ProtoReflect.Descriptor instead.
func (*TestingConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{16}
}

func (x *TestingConfig) GetDefaultFramework() string {
	if x != nil {
		return x.DefaultFramework
	}
	return ""
}

func (x *TestingConfig) GetMinCoverage() int32 {
	if x != nil {
		return x.MinCoverage
	}
	return 0
}

func (x *TestingConfig) GetCoverageFormat() string {
	if x != nil {
		return x.CoverageFormat
	}
	return ""
}

func (x *TestingConfig) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

// MLXConfig contains MLX tool settings
type MLXConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DefaultModel       string                 `protobuf:"bytes,1,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	DefaultMaxTokens   int32                  `protobuf:"varint,2,opt,name=default_max_tokens,json=defaultMaxTokens,proto3" json:"default_max_tokens,omitempty"`
	DefaultTemperature float64                `protobuf:"fixed64,3,opt,name=default_temperature,json=defaultTemperature,proto3" json:"default_temperature,omitempty"`
	Verbose            bool                   `protobuf:"varint,4,opt,name=verbose,proto3" json:"verbose,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MLXConfig) Reset() {
	*x = MLXConfig{}
	mi := &file_proto_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLXConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLXConfig) ProtoMessage() {}

func (x *MLXConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLXConfig.ProtoReflect.Descriptor instead.
func (*MLXConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{17}
}

func (x *MLXConfig) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *MLXConfig) GetDefaultMaxTokens() int32 {
	if x != nil {
		return x.DefaultMaxTokens
	}
	return 0
}

func (x *MLXConfig) GetDefaultTemperature() float64 {
	if x != nil {
		return x.DefaultTemperature
	}
	return 0
}

func (x *MLXConfig) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

// OllamaConfig contains Ollama tool settings
type OllamaConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DefaultModel       string                 `protobuf:"bytes,1,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	DefaultHost        string                 `protobuf:"bytes,2,opt,name=default_host,json=defaultHost,proto3" json:"default_host,omitempty"`
	DefaultContextSize int32                  `protobuf:"varint,3,opt,name=default_context_size,json=defaultContextSize,proto3" json:"default_context_size,omitempty"`
	DefaultNumThreads  int32                  `protobuf:"varint,4,opt,name=default_num_threads,json=defaultNumThreads,proto3" json:"default_num_threads,omitempty"`
	DefaultNumGpu      int32                  `protobuf:"varint,5,opt,name=default_num_gpu,json=defaultNumGpu,proto3" json:"default_num_gpu,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OllamaConfig) Reset() {
	*x = OllamaConfig{}
	mi := &file_proto_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OllamaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OllamaConfig) ProtoMessage() {}

func (x *OllamaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OllamaConfig.ProtoReflect.Descriptor instead.
func (*OllamaConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{18}
}

func (x *OllamaConfig) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *OllamaConfig) GetDefaultHost() string {
	if x != nil {
		return x.DefaultHost
	}
	return ""
}

func (x *OllamaConfig) GetDefaultContextSize() int32 {
	if x != nil {
		return x.DefaultContextSize
	}
	return 0
}

func (x *OllamaConfig) GetDefaultNumThreads() int32 {
	if x != nil {
		return x.DefaultNumThreads
	}
	return 0
}

func (x *OllamaConfig) GetDefaultNumGpu() int32 {
	if x != nil {
		return x.DefaultNumGpu
	}
	return 0
}

// ContextConfig contains context tool settings
type ContextConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	DefaultBudget             int32                  `protobuf:"varint,1,opt,name=default_budget,json=defaultBudget,proto3" json:"default_budget,omitempty"`
	DefaultSummarizationLevel string                 `protobuf:"bytes,2,opt,name=default_summarization_level,json=defaultSummarizationLevel,proto3" json:"default_summarization_level,omitempty"`
	TokensPerChar             float64                `protobuf:"fixed64,3,opt,name=tokens_per_char,json=tokensPerChar,proto3" json:"tokens_per_char,omitempty"`
	IncludeRaw                bool                   `protobuf:"varint,4,opt,name=include_raw,json=includeRaw,proto3" json:"include_raw,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ContextConfig) Reset() {
	*x = ContextConfig{}
	mi := &file_proto_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextConfig) ProtoMessage() {}

func (x *ContextConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextConfig.ProtoReflect.Descriptor instead.
func (*ContextConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{19}
}

func (x *ContextConfig) GetDefaultBudget() int32 {
	if x != nil {
		return x.DefaultBudget
	}
	return 0
}

func (x *ContextConfig) GetDefaultSummarizationLevel() string {
	if x != nil {
		return x.DefaultSummarizationLevel
	}
	return ""
}

func (x *ContextConfig) GetTokensPerChar() float64 {
	if x != nil {
		return x.TokensPerChar
	}
	return 0
}

func (x *ContextConfig) GetIncludeRaw() bool {
	if x != nil {
		return x.IncludeRaw
	}
	return false
}

// WorkflowConfig contains workflow mode settings
type WorkflowConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DefaultMode     string                 `protobuf:"bytes,1,opt,name=default_mode,json=defaultMode,proto3" json:"default_mode,omitempty"`
	AutoDetectMode  bool                   `protobuf:"varint,2,opt,name=auto_detect_mode,json=autoDetectMode,proto3" json:"auto_detect_mode,omitempty"`
	ModeSuggestions *ModeSuggestionsConfig `protobuf:"bytes,3,opt,name=mode_suggestions,json=modeSuggestions,proto3" json:"mode_suggestions,omitempty"`
	// Modes map stored as JSON string for flexibility
	ModesJson     string       `protobuf:"bytes,4,opt,name=modes_json,json=modesJson,proto3" json:"modes_json,omitempty"`
	Focus         *FocusConfig `protobuf:"bytes,5,opt,name=focus,proto3" json:"focus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowConfig) Reset() {
	*x = WorkflowConfig{}
	mi := &file_proto_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowConfig) ProtoMessage() {}

func (x *WorkflowConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowConfig.ProtoReflect.Descriptor instead.
func (*WorkflowConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{20}
}

func (x *WorkflowConfig) GetDefaultMode() string {
	if x != nil {
		return x.DefaultMode
	}
	return ""
}

func (x *WorkflowConfig) GetAutoDetectMode() bool {
	if x != nil {
		return x.AutoDetectMode
	}
	return false
}

func (x *WorkflowConfig) GetModeSuggestions() *ModeSuggestionsConfig {
	if x != nil {
		return x.ModeSuggestions
	}
	return nil
}

func (x *WorkflowConfig) GetModesJson() string {
	if x != nil {
		return x.ModesJson
	}
	return ""
}

func (x *WorkflowConfig) GetFocus() *FocusConfig {
	if x != nil {
		return x.Focus
	}
	return nil
}

// ModeSuggestionsConfig contains time-based mode suggestions
type ModeSuggestionsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Morning       string                 `protobuf:"bytes,1,opt,name=morning,proto3" json:"morning,omitempty"`
	Afternoon     string                 `protobuf:"bytes,2,opt,name=afternoon,proto3" json:"afternoon,omitempty"`
	Evening       string                 `protobuf:"bytes,3,opt,name=evening,proto3" json:"evening,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeSuggestionsConfig) Reset() {
	*x = ModeSuggestionsConfig{}
	mi := &file_proto_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeSuggestionsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeSuggestionsConfig) ProtoMessage() {}

func (x *ModeSuggestionsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeSuggestionsConfig.ProtoReflect.Descriptor instead.
func (*ModeSuggestionsConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{21}
}

func (x *ModeSuggestionsConfig) GetMorning() string {
	if x != nil {
		return x.Morning
	}
	return ""
}

func (x *ModeSuggestionsConfig) GetAfternoon() string {
	if x != nil {
		return x.Afternoon
	}
	return ""
}

func (x *ModeSuggestionsConfig) GetEvening() string {
	if x != nil {
		return x.Evening
	}
	return ""
}

// FocusConfig contains focus mode settings
type FocusConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ReductionTarget   int32                  `protobuf:"varint,2,opt,name=reduction_target,json=reductionTarget,proto3" json:"reduction_target,omitempty"`
	PreserveCoreTools bool                   `protobuf:"varint,3,opt,name=preserve_core_tools,json=preserveCoreTools,proto3" json:"preserve_core_tools,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FocusConfig) Reset() {
	*x = FocusConfig{}
	mi := &file_proto_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusConfig) ProtoMessage() {}

func (x *FocusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusConfig.ProtoReflect.Descriptor instead.
func (*FocusConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{22}
}

func (x *FocusConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FocusConfig) GetReductionTarget() int32 {
	if x != nil {
		return x.ReductionTarget
	}
	return 0
}

func (x *FocusConfig) GetPreserveCoreTools() bool {
	if x != nil {
		return x.PreserveCoreTools
	}
	return false
}

// MemoryConfig contains memory and session settings
type MemoryConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Categories     []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	StoragePath    string                 `protobuf:"bytes,2,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	SessionLogPath string                 `protobuf:"bytes,3,opt,name=session_log_path,json=sessionLogPath,proto3" json:"session_log_path,omitempty"`
	RetentionDays  int32                  `protobuf:"varint,4,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	AutoCleanup    bool                   `protobuf:"varint,5,opt,name=auto_cleanup,json=autoCleanup,proto3" json:"auto_cleanup,omitempty"`
	MaxMemories    int32                  `protobuf:"varint,6,opt,name=max_memories,json=maxMemories,proto3" json:"max_memories,omitempty"`
	Consolidation  *ConsolidationConfig   `protobuf:"bytes,7,opt,name=consolidation,proto3" json:"consolidation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryConfig) Reset() {
	*x = MemoryConfig{}
	mi := &file_proto_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryConfig) ProtoMessage() {}

func (x *MemoryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryConfig.ProtoReflect.Descriptor instead.
func (*MemoryConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{23}
}

func (x *MemoryConfig) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *MemoryConfig) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *MemoryConfig) GetSessionLogPath() string {
	if x != nil {
		return x.SessionLogPath
	}
	return ""
}

func (x *MemoryConfig) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *MemoryConfig) GetAutoCleanup() bool {
	if x != nil {
		return x.AutoCleanup
	}
	return false
}

func (x *MemoryConfig) GetMaxMemories() int32 {
	if x != nil {
		return x.MaxMemories
	}
	return 0
}

func (x *MemoryConfig) GetConsolidation() *ConsolidationConfig {
	if x != nil {
		return x.Consolidation
	}
	return nil
}

// ConsolidationConfig contains memory consolidation settings
type ConsolidationConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SimilarityThreshold float64                `protobuf:"fixed64,2,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	Frequency           string                 `protobuf:"bytes,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConsolidationConfig) Reset() {
	*x = ConsolidationConfig{}
	mi := &file_proto_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidationConfig) ProtoMessage() {}

func (x *ConsolidationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidationConfig.ProtoReflect.Descriptor instead.
func (*ConsolidationConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{24}
}

func (x *ConsolidationConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConsolidationConfig) GetSimilarityThreshold() float64 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

func (x *ConsolidationConfig) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

// ProjectConfig contains project-specific settings
type ProjectConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Root          string                 `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	Todo2Path     string                 `protobuf:"bytes,5,opt,name=todo2_path,json=todo2Path,proto3" json:"todo2_path,omitempty"`
	ExarpPath     string                 `protobuf:"bytes,6,opt,name=exarp_path,json=exarpPath,proto3" json:"exarp_path,omitempty"`
	Features      *FeaturesConfig        `protobuf:"bytes,7,opt,name=features,proto3" json:"features,omitempty"`
	SkipChecks    []string               `protobuf:"bytes,8,rep,name=skip_checks,json=skipChecks,proto3" json:"skip_checks,omitempty"`
	CustomTools   []string               `protobuf:"bytes,9,rep,name=custom_tools,json=customTools,proto3" json:"custom_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectConfig) Reset() {
	*x = ProjectConfig{}
	mi := &file_proto_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfig) ProtoMessage() {}

func (x *ProjectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfig.ProtoReflect.Descriptor instead.
func (*ProjectConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{25}
}

func (x *ProjectConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProjectConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ProjectConfig) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ProjectConfig) GetTodo2Path() string {
	if x != nil {
		return x.Todo2Path
	}
	return ""
}

func (x *ProjectConfig) GetExarpPath() string {
	if x != nil {
		return x.ExarpPath
	}
	return ""
}

func (x *ProjectConfig) GetFeatures() *FeaturesConfig {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ProjectConfig) GetSkipChecks() []string {
	if x != nil {
		return x.SkipChecks
	}
	return nil
}

func (x *ProjectConfig) GetCustomTools() []string {
	if x != nil {
		return x.CustomTools
	}
	return nil
}

// FeaturesConfig contains feature flags
type FeaturesConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SqliteEnabled bool                   `protobuf:"varint,1,opt,name=sqlite_enabled,json=sqliteEnabled,proto3" json:"sqlite_enabled,omitempty"`
	JsonFallback  bool                   `protobuf:"varint,2,opt,name=json_fallback,json=jsonFallback,proto3" json:"json_fallback,omitempty"`
	McpServers    []string               `protobuf:"bytes,4,rep,name=mcp_servers,json=mcpServers,proto3" json:"mcp_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturesConfig) Reset() {
	*x = FeaturesConfig{}
	mi := &file_proto_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturesConfig) ProtoMessage() {}

func (x *FeaturesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturesConfig.ProtoReflect.Descriptor instead.
func (*FeaturesConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{26}
}

func (x *FeaturesConfig) GetSqliteEnabled() bool {
	if x != nil {
		return x.SqliteEnabled
	}
	return false
}

func (x *FeaturesConfig) GetJsonFallback() bool {
	if x != nil {
		return x.JsonFallback
	}
	return false
}

func (x *FeaturesConfig) GetMcpServers() []string {
	if x != nil {
		return x.McpServers
	}
	return nil
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\fexarp.config\"\xd2\x04\n" +
	"\n" +
	"FullConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x128\n" +
	"\btimeouts\x18\x02 \x01(\v2\x1c.exarp.config.TimeoutsConfigR\btimeouts\x12>\n" +
	"\n" +
	"thresholds\x18\x03 \x01(\v2\x1e.exarp.config.ThresholdsConfigR\n" +
	"thresholds\x12/\n" +
	"\x05tasks\x18\x04 \x01(\v2\x19.exarp.config.TasksConfigR\x05tasks\x128\n" +
	"\bdatabase\x18\x05 \x01(\v2\x1c.exarp.config.DatabaseConfigR\bdatabase\x128\n" +
	"\bsecurity\x18\x06 \x01(\v2\x1c.exarp.config.SecurityConfigR\bsecurity\x125\n" +
	"\alogging\x18\a \x01(\v2\x1b.exarp.config.LoggingConfigR\alogging\x12/\n" +
	"\x05tools\x18\b \x01(\v2\x19.exarp.config.ToolsConfigR\x05tools\x128\n" +
	"\bworkflow\x18\t \x01(\v2\x1c.exarp.config.WorkflowConfigR\bworkflow\x122\n" +
	"\x06memory\x18\n" +
	" \x01(\v2\x1a.exarp.config.MemoryConfigR\x06memory\x125\n" +
	"\aproject\x18\v \x01(\v2\x1b.exarp.config.ProjectConfigR\aproject\"\xb5\x04\n" +
	"\x0eTimeoutsConfig\x12&\n" +
	"\x0ftask_lock_lease\x18\x01 \x01(\x03R\rtaskLockLease\x12*\n" +
	"\x11task_lock_renewal\x18\x02 \x01(\x03R\x0ftaskLockRenewal\x120\n" +
	"\x14stale_lock_threshold\x18\x03 \x01(\x03R\x12staleLockThreshold\x12!\n" +
	"\ftool_default\x18\x04 \x01(\x03R\vtoolDefault\x12%\n" +
	"\x0etool_scorecard\x18\x05 \x01(\x03R\rtoolScorecard\x12!\n" +
	"\ftool_linting\x18\x06 \x01(\x03R\vtoolLinting\x12!\n" +
	"\ftool_testing\x18\a \x01(\x03R\vtoolTesting\x12\x1f\n" +
	"\vtool_report\x18\b \x01(\x03R\n" +
	"toolReport\x12'\n" +
	"\x0follama_download\x18\t \x01(\x03R\x0eollamaDownload\x12'\n" +
	"\x0follama_generate\x18\n" +
	" \x01(\x03R\x0eollamaGenerate\x12\x1f\n" +
	"\vhttp_client\x18\v \x01(\x03R\n" +
	"httpClient\x12%\n" +
	"\x0edatabase_retry\x18\f \x01(\x03R\rdatabaseRetry\x12+\n" +
	"\x11context_summarize\x18\r \x01(\x03R\x10contextSummarize\x12%\n" +
	"\x0econtext_budget\x18\x0e \x01(\x03R\rcontextBudget\"\xe1\x06\n" +
	"\x10ThresholdsConfig\x121\n" +
	"\x14similarity_threshold\x18\x01 \x01(\x01R\x13similarityThreshold\x124\n" +
	"\x16min_description_length\x18\x02 \x01(\x05R\x14minDescriptionLength\x12.\n" +
	"\x13min_task_confidence\x18\x03 \x01(\x01R\x11minTaskConfidence\x12!\n" +
	"\fmin_coverage\x18\x04 \x01(\x05R\vminCoverage\x12.\n" +
	"\x13min_test_confidence\x18\x05 \x01(\x01R\x11minTestConfidence\x12:\n" +
	"\x19min_estimation_confidence\x18\x06 \x01(\x01R\x17minEstimationConfidence\x12\x1d\n" +
	"\n" +
	"mlx_weight\x18\a \x01(\x01R\tmlxWeight\x12,\n" +
	"\x12max_parallel_tasks\x18\b \x01(\x05R\x10maxParallelTasks\x12+\n" +
	"\x12max_tasks_per_host\x18\t \x01(\x05R\x0fmaxTasksPerHost\x12:\n" +
	"\x19max_automation_iterations\x18\n" +
	" \x01(\x05R\x17maxAutomationIterations\x12+\n" +
	"\x12max_tasks_per_wave\x18\x12 \x01(\x05R\x0fmaxTasksPerWave\x12&\n" +
	"\x0ftokens_per_char\x18\v \x01(\x01R\rtokensPerChar\x124\n" +
	"\x16default_context_budget\x18\f \x01(\x05R\x14defaultContextBudget\x12>\n" +
	"\x1bcontext_reduction_threshold\x18\r \x01(\x01R\x19contextReductionThreshold\x12.\n" +
	"\x13rate_limit_requests\x18\x0e \x01(\x05R\x11rateLimitRequests\x12*\n" +
	"\x11rate_limit_window\x18\x0f \x01(\x03R\x0frateLimitWindow\x12\"\n" +
	"\rmax_file_size\x18\x10 \x01(\x03R\vmaxFileSize\x12$\n" +
	"\x0emax_path_depth\x18\x11 \x01(\x05R\fmaxPathDepth\"\x86\x04\n" +
	"\vTasksConfig\x12%\n" +
	"\x0edefault_status\x18\x01 \x01(\tR\rdefaultStatus\x12)\n" +
	"\x10default_priority\x18\x02 \x01(\tR\x0fdefaultPriority\x12!\n" +
	"\fdefault_tags\x18\x03 \x03(\tR\vdefaultTags\x120\n" +
	"\x14status_workflow_json\x18\x04 \x01(\tR\x12statusWorkflowJson\x122\n" +
	"\x15stale_threshold_hours\x18\x05 \x01(\x05R\x13staleThresholdHours\x120\n" +
	"\x14auto_cleanup_enabled\x18\x06 \x01(\bR\x12autoCleanupEnabled\x12&\n" +
	"\x0fcleanup_dry_run\x18\a \x01(\bR\rcleanupDryRun\x12\x1b\n" +
	"\tid_format\x18\b \x01(\tR\bidFormat\x12\x1b\n" +
	"\tid_prefix\x18\t \x01(\tR\bidPrefix\x124\n" +
	"\x16min_description_length\x18\n" +
	" \x01(\x05R\x14minDescriptionLength\x12/\n" +
	"\x13require_description\x18\v \x01(\bR\x12requireDescription\x12!\n" +
	"\fauto_clarify\x18\f \x01(\bR\vautoClarify\"\xc8\x04\n" +
	"\x0eDatabaseConfig\x12\x1f\n" +
	"\vsqlite_path\x18\x01 \x01(\tR\n" +
	"sqlitePath\x12,\n" +
	"\x12json_fallback_path\x18\x02 \x01(\tR\x10jsonFallbackPath\x12\x1f\n" +
	"\vbackup_path\x18\x03 \x01(\tR\n" +
	"backupPath\x12'\n" +
	"\x0fmax_connections\x18\x04 \x01(\x05R\x0emaxConnections\x12-\n" +
	"\x12connection_timeout\x18\x05 \x01(\x03R\x11connectionTimeout\x12#\n" +
	"\rquery_timeout\x18\x06 \x01(\x03R\fqueryTimeout\x12%\n" +
	"\x0eretry_attempts\x18\a \x01(\x05R\rretryAttempts\x12.\n" +
	"\x13retry_initial_delay\x18\b \x01(\x03R\x11retryInitialDelay\x12&\n" +
	"\x0fretry_max_delay\x18\t \x01(\x03R\rretryMaxDelay\x12)\n" +
	"\x10retry_multiplier\x18\n" +
	" \x01(\x01R\x0fretryMultiplier\x12\x1f\n" +
	"\vauto_vacuum\x18\v \x01(\bR\n" +
	"autoVacuum\x12\x19\n" +
	"\bwal_mode\x18\f \x01(\bR\awalMode\x12/\n" +
	"\x13checkpoint_interval\x18\r \x01(\x05R\x12checkpointInterval\x122\n" +
	"\x15backup_retention_days\x18\x0e \x01(\x05R\x13backupRetentionDays\"\xa6\x02\n" +
	"\x0eSecurityConfig\x12<\n" +
	"\n" +
	"rate_limit\x18\x01 \x01(\v2\x1d.exarp.config.RateLimitConfigR\trateLimit\x12K\n" +
	"\x0fpath_validation\x18\x02 \x01(\v2\".exarp.config.PathValidationConfigR\x0epathValidation\x12?\n" +
	"\vfile_limits\x18\x03 \x01(\v2\x1e.exarp.config.FileLimitsConfigR\n" +
	"fileLimits\x12H\n" +
	"\x0eaccess_control\x18\x04 \x01(\v2!.exarp.config.AccessControlConfigR\raccessControl\"\xa3\x01\n" +
	"\x0fRateLimitConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12.\n" +
	"\x13requests_per_window\x18\x02 \x01(\x05R\x11requestsPerWindow\x12'\n" +
	"\x0fwindow_duration\x18\x03 \x01(\x03R\x0ewindowDuration\x12\x1d\n" +
	"\n" +
	"burst_size\x18\x04 \x01(\x05R\tburstSize\"\xaa\x01\n" +
	"\x14PathValidationConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x120\n" +
	"\x14allow_absolute_paths\x18\x02 \x01(\bR\x12allowAbsolutePaths\x12\x1b\n" +
	"\tmax_depth\x18\x03 \x01(\x05R\bmaxDepth\x12)\n" +
	"\x10blocked_patterns\x18\x04 \x03(\tR\x0fblockedPatterns\"\x9c\x01\n" +
	"\x10FileLimitsConfig\x12\"\n" +
	"\rmax_file_size\x18\x01 \x01(\x03R\vmaxFileSize\x125\n" +
	"\x17max_files_per_operation\x18\x02 \x01(\x05R\x14maxFilesPerOperation\x12-\n" +
	"\x12allowed_extensions\x18\x03 \x03(\tR\x11allowedExtensions\"\x81\x01\n" +
	"\x13AccessControlConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12%\n" +
	"\x0edefault_policy\x18\x02 \x01(\tR\rdefaultPolicy\x12)\n" +
	"\x10restricted_tools\x18\x03 \x03(\tR\x0frestrictedTools\"\xe8\x03\n" +
	"\rLoggingConfig\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"tool_level\x18\x02 \x01(\tR\ttoolLevel\x12'\n" +
	"\x0fframework_level\x18\x03 \x01(\tR\x0eframeworkLevel\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12-\n" +
	"\x12include_timestamps\x18\x05 \x01(\bR\x11includeTimestamps\x12%\n" +
	"\x0einclude_caller\x18\x06 \x01(\bR\rincludeCaller\x12!\n" +
	"\fcolor_output\x18\a \x01(\bR\vcolorOutput\x12\x17\n" +
	"\alog_dir\x18\b \x01(\tR\x06logDir\x12\x19\n" +
	"\blog_file\x18\t \x01(\tR\alogFile\x12&\n" +
	"\x0fsession_log_dir\x18\n" +
	" \x01(\tR\rsessionLogDir\x12B\n" +
	"\flog_rotation\x18\v \x01(\v2\x1f.exarp.config.LogRotationConfigR\vlogRotation\x12%\n" +
	"\x0eretention_days\x18\f \x01(\x05R\rretentionDays\x12!\n" +
	"\fauto_cleanup\x18\r \x01(\bR\vautoCleanup\"\x81\x01\n" +
	"\x11LogRotationConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x19\n" +
	"\bmax_size\x18\x02 \x01(\x03R\amaxSize\x12\x1b\n" +
	"\tmax_files\x18\x03 \x01(\x05R\bmaxFiles\x12\x1a\n" +
	"\bcompress\x18\x04 \x01(\bR\bcompress\"\x82\x03\n" +
	"\vToolsConfig\x12;\n" +
	"\tscorecard\x18\x01 \x01(\v2\x1d.exarp.config.ScorecardConfigR\tscorecard\x122\n" +
	"\x06report\x18\x02 \x01(\v2\x1a.exarp.config.ReportConfigR\x06report\x125\n" +
	"\alinting\x18\x03 \x01(\v2\x1b.exarp.config.LintingConfigR\alinting\x125\n" +
	"\atesting\x18\x04 \x01(\v2\x1b.exarp.config.TestingConfigR\atesting\x12)\n" +
	"\x03mlx\x18\x05 \x01(\v2\x17.exarp.config.MLXConfigR\x03mlx\x122\n" +
	"\x06ollama\x18\x06 \x01(\v2\x1a.exarp.config.OllamaConfigR\x06ollama\x125\n" +
	"\acontext\x18\a \x01(\v2\x1b.exarp.config.ContextConfigR\acontext\"\x8d\x01\n" +
	"\x0fScorecardConfig\x12.\n" +
	"\x13default_scores_json\x18\x01 \x01(\tR\x11defaultScoresJson\x12%\n" +
	"\x0einclude_wisdom\x18\x02 \x01(\bR\rincludeWisdom\x12#\n" +
	"\routput_format\x18\x03 \x01(\tR\foutputFormat\"\xc7\x01\n" +
	"\fReportConfig\x12%\n" +
	"\x0edefault_format\x18\x01 \x01(\tR\rdefaultFormat\x12.\n" +
	"\x13default_output_path\x18\x02 \x01(\tR\x11defaultOutputPath\x12'\n" +
	"\x0finclude_metrics\x18\x03 \x01(\bR\x0eincludeMetrics\x127\n" +
	"\x17include_recommendations\x18\x04 \x01(\bR\x16includeRecommendations\"\x90\x01\n" +
	"\rLintingConfig\x12%\n" +
	"\x0edefault_linter\x18\x01 \x01(\tR\rdefaultLinter\x12\x19\n" +
	"\bauto_fix\x18\x02 \x01(\bR\aautoFix\x12#\n" +
	"\rinclude_hints\x18\x03 \x01(\bR\fincludeHints\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\"\xa2\x01\n" +
	"\rTestingConfig\x12+\n" +
	"\x11default_framework\x18\x01 \x01(\tR\x10defaultFramework\x12!\n" +
	"\fmin_coverage\x18\x02 \x01(\x05R\vminCoverage\x12'\n" +
	"\x0fcoverage_format\x18\x03 \x01(\tR\x0ecoverageFormat\x12\x18\n" +
	"\averbose\x18\x04 \x01(\bR\averbose\"\xa9\x01\n" +
	"\tMLXConfig\x12#\n" +
	"\rdefault_model\x18\x01 \x01(\tR\fdefaultModel\x12,\n" +
	"\x12default_max_tokens\x18\x02 \x01(\x05R\x10defaultMaxTokens\x12/\n" +
	"\x13default_temperature\x18\x03 \x01(\x01R\x12defaultTemperature\x12\x18\n" +
	"\averbose\x18\x04 \x01(\bR\averbose\"\xe0\x01\n" +
	"\fOllamaConfig\x12#\n" +
	"\rdefault_model\x18\x01 \x01(\tR\fdefaultModel\x12!\n" +
	"\fdefault_host\x18\x02 \x01(\tR\vdefaultHost\x120\n" +
	"\x14default_context_size\x18\x03 \x01(\x05R\x12defaultContextSize\x12.\n" +
	"\x13default_num_threads\x18\x04 \x01(\x05R\x11defaultNumThreads\x12&\n" +
	"\x0fdefault_num_gpu\x18\x05 \x01(\x05R\rdefaultNumGpu\"\xbf\x01\n" +
	"\rContextConfig\x12%\n" +
	"\x0edefault_budget\x18\x01 \x01(\x05R\rdefaultBudget\x12>\n" +
	"\x1bdefault_summarization_level\x18\x02 \x01(\tR\x19defaultSummarizationLevel\x12&\n" +
	"\x0ftokens_per_char\x18\x03 \x01(\x01R\rtokensPerChar\x12\x1f\n" +
	"\vinclude_raw\x18\x04 \x01(\bR\n" +
	"includeRaw\"\xfd\x01\n" +
	"\x0eWorkflowConfig\x12!\n" +
	"\fdefault_mode\x18\x01 \x01(\tR\vdefaultMode\x12(\n" +
	"\x10auto_detect_mode\x18\x02 \x01(\bR\x0eautoDetectMode\x12N\n" +
	"\x10mode_suggestions\x18\x03 \x01(\v2#.exarp.config.ModeSuggestionsConfigR\x0fmodeSuggestions\x12\x1d\n" +
	"\n" +
	"modes_json\x18\x04 \x01(\tR\tmodesJson\x12/\n" +
	"\x05focus\x18\x05 \x01(\v2\x19.exarp.config.FocusConfigR\x05focus\"i\n" +
	"\x15ModeSuggestionsConfig\x12\x18\n" +
	"\amorning\x18\x01 \x01(\tR\amorning\x12\x1c\n" +
	"\tafternoon\x18\x02 \x01(\tR\tafternoon\x12\x18\n" +
	"\aevening\x18\x03 \x01(\tR\aevening\"\x82\x01\n" +
	"\vFocusConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10reduction_target\x18\x02 \x01(\x05R\x0freductionTarget\x12.\n" +
	"\x13preserve_core_tools\x18\x03 \x01(\bR\x11preserveCoreTools\"\xb1\x02\n" +
	"\fMemoryConfig\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\x12!\n" +
	"\fstorage_path\x18\x02 \x01(\tR\vstoragePath\x12(\n" +
	"\x10session_log_path\x18\x03 \x01(\tR\x0esessionLogPath\x12%\n" +
	"\x0eretention_days\x18\x04 \x01(\x05R\rretentionDays\x12!\n" +
	"\fauto_cleanup\x18\x05 \x01(\bR\vautoCleanup\x12!\n" +
	"\fmax_memories\x18\x06 \x01(\x05R\vmaxMemories\x12G\n" +
	"\rconsolidation\x18\a \x01(\v2!.exarp.config.ConsolidationConfigR\rconsolidation\"\x80\x01\n" +
	"\x13ConsolidationConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x121\n" +
	"\x14similarity_threshold\x18\x02 \x01(\x01R\x13similarityThreshold\x12\x1c\n" +
	"\tfrequency\x18\x03 \x01(\tR\tfrequency\"\xa3\x02\n" +
	"\rProjectConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04root\x18\x04 \x01(\tR\x04root\x12\x1d\n" +
	"\n" +
	"todo2_path\x18\x05 \x01(\tR\ttodo2Path\x12\x1d\n" +
	"\n" +
	"exarp_path\x18\x06 \x01(\tR\texarpPath\x128\n" +
	"\bfeatures\x18\a \x01(\v2\x1c.exarp.config.FeaturesConfigR\bfeatures\x12\x1f\n" +
	"\vskip_checks\x18\b \x03(\tR\n" +
	"skipChecks\x12!\n" +
	"\fcustom_tools\x18\t \x03(\tR\vcustomTools\"}\n" +
	"\x0eFeaturesConfig\x12%\n" +
	"\x0esqlite_enabled\x18\x01 \x01(\bR\rsqliteEnabled\x12#\n" +
	"\rjson_fallback\x18\x02 \x01(\bR\fjsonFallback\x12\x1f\n" +
	"\vmcp_servers\x18\x04 \x03(\tR\n" +
	"mcpServersB$Z\"github.com/davidl71/exarp-go/protob\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_config_proto_goTypes = []any{
	(*FullConfig)(nil),            // 0: exarp.config.FullConfig
	(*TimeoutsConfig)(nil),        // 1: exarp.config.TimeoutsConfig
	(*ThresholdsConfig)(nil),      // 2: exarp.config.ThresholdsConfig
	(*TasksConfig)(nil),           // 3: exarp.config.TasksConfig
	(*DatabaseConfig)(nil),        // 4: exarp.config.DatabaseConfig
	(*SecurityConfig)(nil),        // 5: exarp.config.SecurityConfig
	(*RateLimitConfig)(nil),       // 6: exarp.config.RateLimitConfig
	(*PathValidationConfig)(nil),  // 7: exarp.config.PathValidationConfig
	(*FileLimitsConfig)(nil),      // 8: exarp.config.FileLimitsConfig
	(*AccessControlConfig)(nil),   // 9: exarp.config.AccessControlConfig
	(*LoggingConfig)(nil),         // 10: exarp.config.LoggingConfig
	(*LogRotationConfig)(nil),     // 11: exarp.config.LogRotationConfig
	(*ToolsConfig)(nil),           // 12: exarp.config.ToolsConfig
	(*ScorecardConfig)(nil),       // 13: exarp.config.ScorecardConfig
	(*ReportConfig)(nil),          // 14: exarp.config.ReportConfig
	(*LintingConfig)(nil),         // 15: exarp.config.LintingConfig
	(*TestingConfig)(nil),         // 16: exarp.config.TestingConfig
	(*MLXConfig)(nil),             // 17: exarp.config.MLXConfig
	(*OllamaConfig)(nil),          // 18: exarp.config.OllamaConfig
	(*ContextConfig)(nil),         // 19: exarp.config.ContextConfig
	(*WorkflowConfig)(nil),        // 20: exarp.config.WorkflowConfig
	(*ModeSuggestionsConfig)(nil), // 21: exarp.config.ModeSuggestionsConfig
	(*FocusConfig)(nil),           // 22: exarp.config.FocusConfig
	(*MemoryConfig)(nil),          // 23: exarp.config.MemoryConfig
	(*ConsolidationConfig)(nil),   // 24: exarp.config.ConsolidationConfig
	(*ProjectConfig)(nil),         // 25: exarp.config.ProjectConfig
	(*FeaturesConfig)(nil),        // 26: exarp.config.FeaturesConfig
}
var file_proto_config_proto_depIdxs = []int32{
	1,  // 0: exarp.config.FullConfig.timeouts:type_name -> exarp.config.TimeoutsConfig
	2,  // 1: exarp.config.FullConfig.thresholds:type_name -> exarp.config.ThresholdsConfig
	3,  // 2: exarp.config.FullConfig.tasks:type_name -> exarp.config.TasksConfig
	4,  // 3: exarp.config.FullConfig.database:type_name -> exarp.config.DatabaseConfig
	5,  // 4: exarp.config.FullConfig.security:type_name -> exarp.config.SecurityConfig
	10, // 5: exarp.config.FullConfig.logging:type_name -> exarp.config.LoggingConfig
	12, // 6: exarp.config.FullConfig.tools:type_name -> exarp.config.ToolsConfig
	20, // 7: exarp.config.FullConfig.workflow:type_name -> exarp.config.WorkflowConfig
	23, // 8: exarp.config.FullConfig.memory:type_name -> exarp.config.MemoryConfig
	25, // 9: exarp.config.FullConfig.project:type_name -> exarp.config.ProjectConfig
	6,  // 10: exarp.config.SecurityConfig.rate_limit:type_name -> exarp.config.RateLimitConfig
	7,  // 11: exarp.config.SecurityConfig.path_validation:type_name -> exarp.config.PathValidationConfig
	8,  // 12: exarp.config.SecurityConfig.file_limits:type_name -> exarp.config.FileLimitsConfig
	9,  // 13: exarp.config.SecurityConfig.access_control:type_name -> exarp.config.AccessControlConfig
	11, // 14: exarp.config.LoggingConfig.log_rotation:type_name -> exarp.config.LogRotationConfig
	13, // 15: exarp.config.ToolsConfig.scorecard:type_name -> exarp.config.ScorecardConfig
	14, // 16: exarp.config.ToolsConfig.report:type_name -> exarp.config.ReportConfig
	15, // 17: exarp.config.ToolsConfig.linting:type_name -> exarp.config.LintingConfig
	16, // 18: exarp.config.ToolsConfig.testing:type_name -> exarp.config.TestingConfig
	17, // 19: exarp.config.ToolsConfig.mlx:type_name -> exarp.config.MLXConfig
	18, // 20: exarp.config.ToolsConfig.ollama:type_name -> exarp.config.OllamaConfig
	19, // 21: exarp.config.ToolsConfig.context:type_name -> exarp.config.ContextConfig
	21, // 22: exarp.config.WorkflowConfig.mode_suggestions:type_name -> exarp.config.ModeSuggestionsConfig
	22, // 23: exarp.config.WorkflowConfig.focus:type_name -> exarp.config.FocusConfig
	24, // 24: exarp.config.MemoryConfig.consolidation:type_name -> exarp.config.ConsolidationConfig
	26, // 25: exarp.config.ProjectConfig.features:type_name -> exarp.config.FeaturesConfig
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
