// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/todo2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Todo2Task represents a Todo2 task with all its metadata
type Todo2Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique task identifier (e.g., "T-123" or epoch-based ID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Short task name/content
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Detailed task description (optional)
	LongDescription string `protobuf:"bytes,3,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	// Task status (e.g., "Todo", "In Progress", "Review", "Done")
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Task priority (e.g., "low", "medium", "high", "critical")
	Priority string `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// List of tags associated with the task
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// List of task IDs this task depends on
	Dependencies []string `protobuf:"bytes,7,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// Whether the task is completed
	Completed bool `protobuf:"varint,8,opt,name=completed,proto3" json:"completed,omitempty"`
	// Additional metadata as key-value pairs (JSON values stored as strings)
	// For complex values, serialize to JSON string
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Creation timestamp (Unix timestamp in seconds)
	CreatedAt int64 `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification timestamp (Unix timestamp in seconds)
	UpdatedAt int64 `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Distributed tracking (for aggregation across projects/hosts/agents)
	ProjectId     string `protobuf:"bytes,12,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`    // Logical project identifier (e.g. "exarp-go")
	AssignedTo    string `protobuf:"bytes,13,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"` // Persistent assignee (owner); distinct from lock assignee
	Host          string `protobuf:"bytes,14,opt,name=host,proto3" json:"host,omitempty"`                               // Hostname where task was created or last modified
	Agent         string `protobuf:"bytes,15,opt,name=agent,proto3" json:"agent,omitempty"`                             // Agent ID that created or last modified (e.g. general-host-pid)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo2Task) Reset() {
	*x = Todo2Task{}
	mi := &file_proto_todo2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo2Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo2Task) ProtoMessage() {}

func (x *Todo2Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo2Task.ProtoReflect.Descriptor instead.
func (*Todo2Task) Descriptor() ([]byte, []int) {
	return file_proto_todo2_proto_rawDescGZIP(), []int{0}
}

func (x *Todo2Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo2Task) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Todo2Task) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *Todo2Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Todo2Task) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Todo2Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Todo2Task) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Todo2Task) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Todo2Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Todo2Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Todo2Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Todo2Task) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Todo2Task) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Todo2Task) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Todo2Task) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

// Todo2State represents the complete Todo2 state file structure
type Todo2State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of all tasks
	Todos []*Todo2Task `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	// Version of the state format (for future compatibility)
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp when state was last saved
	LastSaved     int64 `protobuf:"varint,3,opt,name=last_saved,json=lastSaved,proto3" json:"last_saved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo2State) Reset() {
	*x = Todo2State{}
	mi := &file_proto_todo2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo2State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo2State) ProtoMessage() {}

func (x *Todo2State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo2State.ProtoReflect.Descriptor instead.
func (*Todo2State) Descriptor() ([]byte, []int) {
	return file_proto_todo2_proto_rawDescGZIP(), []int{1}
}

func (x *Todo2State) GetTodos() []*Todo2Task {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *Todo2State) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Todo2State) GetLastSaved() int64 {
	if x != nil {
		return x.LastSaved
	}
	return 0
}

var File_proto_todo2_proto protoreflect.FileDescriptor

const file_proto_todo2_proto_rawDesc = "" +
	"\n" +
	"\x11proto/todo2.proto\x12\vexarp.todo2\"\x91\x04\n" +
	"\tTodo2Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12)\n" +
	"\x10long_description\x18\x03 \x01(\tR\x0flongDescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\"\n" +
	"\fdependencies\x18\a \x03(\tR\fdependencies\x12\x1c\n" +
	"\tcompleted\x18\b \x01(\bR\tcompleted\x12@\n" +
	"\bmetadata\x18\t \x03(\v2$.exarp.todo2.Todo2Task.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"project_id\x18\f \x01(\tR\tprojectId\x12\x1f\n" +
	"\vassigned_to\x18\r \x01(\tR\n" +
	"assignedTo\x12\x12\n" +
	"\x04host\x18\x0e \x01(\tR\x04host\x12\x14\n" +
	"\x05agent\x18\x0f \x01(\tR\x05agent\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\n" +
	"Todo2State\x12,\n" +
	"\x05todos\x18\x01 \x03(\v2\x16.exarp.todo2.Todo2TaskR\x05todos\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"last_saved\x18\x03 \x01(\x03R\tlastSavedB$Z\"github.com/davidl71/exarp-go/protob\x06proto3"

var (
	file_proto_todo2_proto_rawDescOnce sync.Once
	file_proto_todo2_proto_rawDescData []byte
)

func file_proto_todo2_proto_rawDescGZIP() []byte {
	file_proto_todo2_proto_rawDescOnce.Do(func() {
		file_proto_todo2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_todo2_proto_rawDesc), len(file_proto_todo2_proto_rawDesc)))
	})
	return file_proto_todo2_proto_rawDescData
}

var file_proto_todo2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_todo2_proto_goTypes = []any{
	(*Todo2Task)(nil),  // 0: exarp.todo2.Todo2Task
	(*Todo2State)(nil), // 1: exarp.todo2.Todo2State
	nil,                // 2: exarp.todo2.Todo2Task.MetadataEntry
}
var file_proto_todo2_proto_depIdxs = []int32{
	2, // 0: exarp.todo2.Todo2Task.metadata:type_name -> exarp.todo2.Todo2Task.MetadataEntry
	0, // 1: exarp.todo2.Todo2State.todos:type_name -> exarp.todo2.Todo2Task
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_todo2_proto_init() }
func file_proto_todo2_proto_init() {
	if File_proto_todo2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_todo2_proto_rawDesc), len(file_proto_todo2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_todo2_proto_goTypes,
		DependencyIndexes: file_proto_todo2_proto_depIdxs,
		MessageInfos:      file_proto_todo2_proto_msgTypes,
	}.Build()
	File_proto_todo2_proto = out.File
	file_proto_todo2_proto_goTypes = nil
	file_proto_todo2_proto_depIdxs = nil
}
