// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/todo2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Todo2TaskStatus is the typed status of a task.
//
// Note: We keep the legacy string `status` field for JSON/MCP edge compatibility.
// Internal paths should prefer `status_enum`.
type Todo2TaskStatus int32

const (
	Todo2TaskStatus_TODO2_TASK_STATUS_UNSPECIFIED Todo2TaskStatus = 0
	Todo2TaskStatus_TODO2_TASK_STATUS_TODO        Todo2TaskStatus = 1
	Todo2TaskStatus_TODO2_TASK_STATUS_IN_PROGRESS Todo2TaskStatus = 2
	Todo2TaskStatus_TODO2_TASK_STATUS_REVIEW      Todo2TaskStatus = 3
	Todo2TaskStatus_TODO2_TASK_STATUS_DONE        Todo2TaskStatus = 4
	Todo2TaskStatus_TODO2_TASK_STATUS_BLOCKED     Todo2TaskStatus = 5
	Todo2TaskStatus_TODO2_TASK_STATUS_CANCELLED   Todo2TaskStatus = 6
)

// Enum value maps for Todo2TaskStatus.
var (
	Todo2TaskStatus_name = map[int32]string{
		0: "TODO2_TASK_STATUS_UNSPECIFIED",
		1: "TODO2_TASK_STATUS_TODO",
		2: "TODO2_TASK_STATUS_IN_PROGRESS",
		3: "TODO2_TASK_STATUS_REVIEW",
		4: "TODO2_TASK_STATUS_DONE",
		5: "TODO2_TASK_STATUS_BLOCKED",
		6: "TODO2_TASK_STATUS_CANCELLED",
	}
	Todo2TaskStatus_value = map[string]int32{
		"TODO2_TASK_STATUS_UNSPECIFIED": 0,
		"TODO2_TASK_STATUS_TODO":        1,
		"TODO2_TASK_STATUS_IN_PROGRESS": 2,
		"TODO2_TASK_STATUS_REVIEW":      3,
		"TODO2_TASK_STATUS_DONE":        4,
		"TODO2_TASK_STATUS_BLOCKED":     5,
		"TODO2_TASK_STATUS_CANCELLED":   6,
	}
)

func (x Todo2TaskStatus) Enum() *Todo2TaskStatus {
	p := new(Todo2TaskStatus)
	*p = x
	return p
}

func (x Todo2TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Todo2TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_todo2_proto_enumTypes[0].Descriptor()
}

func (Todo2TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_todo2_proto_enumTypes[0]
}

func (x Todo2TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Todo2TaskStatus.Descriptor instead.
func (Todo2TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_todo2_proto_rawDescGZIP(), []int{0}
}

// Todo2TaskPriority is the typed priority of a task.
//
// Note: We keep the legacy string `priority` field for JSON/MCP edge compatibility.
// Internal paths should prefer `priority_enum`.
type Todo2TaskPriority int32

const (
	Todo2TaskPriority_TODO2_TASK_PRIORITY_UNSPECIFIED Todo2TaskPriority = 0
	Todo2TaskPriority_TODO2_TASK_PRIORITY_LOW         Todo2TaskPriority = 1
	Todo2TaskPriority_TODO2_TASK_PRIORITY_MEDIUM      Todo2TaskPriority = 2
	Todo2TaskPriority_TODO2_TASK_PRIORITY_HIGH        Todo2TaskPriority = 3
	Todo2TaskPriority_TODO2_TASK_PRIORITY_CRITICAL    Todo2TaskPriority = 4
)

// Enum value maps for Todo2TaskPriority.
var (
	Todo2TaskPriority_name = map[int32]string{
		0: "TODO2_TASK_PRIORITY_UNSPECIFIED",
		1: "TODO2_TASK_PRIORITY_LOW",
		2: "TODO2_TASK_PRIORITY_MEDIUM",
		3: "TODO2_TASK_PRIORITY_HIGH",
		4: "TODO2_TASK_PRIORITY_CRITICAL",
	}
	Todo2TaskPriority_value = map[string]int32{
		"TODO2_TASK_PRIORITY_UNSPECIFIED": 0,
		"TODO2_TASK_PRIORITY_LOW":         1,
		"TODO2_TASK_PRIORITY_MEDIUM":      2,
		"TODO2_TASK_PRIORITY_HIGH":        3,
		"TODO2_TASK_PRIORITY_CRITICAL":    4,
	}
)

func (x Todo2TaskPriority) Enum() *Todo2TaskPriority {
	p := new(Todo2TaskPriority)
	*p = x
	return p
}

func (x Todo2TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Todo2TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_todo2_proto_enumTypes[1].Descriptor()
}

func (Todo2TaskPriority) Type() protoreflect.EnumType {
	return &file_proto_todo2_proto_enumTypes[1]
}

func (x Todo2TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Todo2TaskPriority.Descriptor instead.
func (Todo2TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_proto_todo2_proto_rawDescGZIP(), []int{1}
}

// Todo2Task represents a Todo2 task with all its metadata
type Todo2Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique task identifier (e.g., "T-123" or epoch-based ID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Short task name/title (optional). Intended for list views and external consumers.
	// content remains the canonical task title used throughout the app/CLI.
	Name string `protobuf:"bytes,16,opt,name=name,proto3" json:"name,omitempty"`
	// Short task name/content
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Detailed task description (optional)
	LongDescription string `protobuf:"bytes,3,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	// Task status (e.g., "Todo", "In Progress", "Review", "Done")
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Typed status (preferred for internal use).
	StatusEnum Todo2TaskStatus `protobuf:"varint,17,opt,name=status_enum,json=statusEnum,proto3,enum=exarp.todo2.Todo2TaskStatus" json:"status_enum,omitempty"`
	// Task priority (e.g., "low", "medium", "high", "critical")
	Priority string `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// Typed priority (preferred for internal use).
	PriorityEnum Todo2TaskPriority `protobuf:"varint,18,opt,name=priority_enum,json=priorityEnum,proto3,enum=exarp.todo2.Todo2TaskPriority" json:"priority_enum,omitempty"`
	// Numeric sort key within the same named priority (low/medium/high/critical).
	// Lower values order earlier after priority tiering (claim, backlog, list).
	PriorityRank int32 `protobuf:"varint,19,opt,name=priority_rank,json=priorityRank,proto3" json:"priority_rank,omitempty"`
	// List of tags associated with the task
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// List of task IDs this task depends on
	Dependencies []string `protobuf:"bytes,7,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// Whether the task is completed
	Completed bool `protobuf:"varint,8,opt,name=completed,proto3" json:"completed,omitempty"`
	// Additional metadata as key-value pairs (JSON values stored as strings)
	// For complex values, serialize to JSON string
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Distributed tracking (for aggregation across projects/hosts/agents)
	ProjectId     string `protobuf:"bytes,12,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`    // Logical project identifier (e.g. "exarp-go")
	AssignedTo    string `protobuf:"bytes,13,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"` // Persistent assignee (owner); distinct from lock assignee
	Host          string `protobuf:"bytes,14,opt,name=host,proto3" json:"host,omitempty"`                               // Hostname where task was created or last modified
	Agent         string `protobuf:"bytes,15,opt,name=agent,proto3" json:"agent,omitempty"`                             // Agent ID that created or last modified (e.g. general-host-pid)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo2Task) Reset() {
	*x = Todo2Task{}
	mi := &file_proto_todo2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo2Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo2Task) ProtoMessage() {}

func (x *Todo2Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo2Task.ProtoReflect.Descriptor instead.
func (*Todo2Task) Descriptor() ([]byte, []int) {
	return file_proto_todo2_proto_rawDescGZIP(), []int{0}
}

func (x *Todo2Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo2Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Todo2Task) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Todo2Task) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *Todo2Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Todo2Task) GetStatusEnum() Todo2TaskStatus {
	if x != nil {
		return x.StatusEnum
	}
	return Todo2TaskStatus_TODO2_TASK_STATUS_UNSPECIFIED
}

func (x *Todo2Task) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Todo2Task) GetPriorityEnum() Todo2TaskPriority {
	if x != nil {
		return x.PriorityEnum
	}
	return Todo2TaskPriority_TODO2_TASK_PRIORITY_UNSPECIFIED
}

func (x *Todo2Task) GetPriorityRank() int32 {
	if x != nil {
		return x.PriorityRank
	}
	return 0
}

func (x *Todo2Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Todo2Task) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Todo2Task) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Todo2Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Todo2Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Todo2Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Todo2Task) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Todo2Task) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Todo2Task) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Todo2Task) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

// Todo2State represents the complete Todo2 state file structure
type Todo2State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of all tasks
	Todos []*Todo2Task `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	// Version of the state format (for future compatibility)
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp when state was last saved
	LastSaved     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_saved,json=lastSaved,proto3" json:"last_saved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo2State) Reset() {
	*x = Todo2State{}
	mi := &file_proto_todo2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo2State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo2State) ProtoMessage() {}

func (x *Todo2State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo2State.ProtoReflect.Descriptor instead.
func (*Todo2State) Descriptor() ([]byte, []int) {
	return file_proto_todo2_proto_rawDescGZIP(), []int{1}
}

func (x *Todo2State) GetTodos() []*Todo2Task {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *Todo2State) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Todo2State) GetLastSaved() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSaved
	}
	return nil
}

var File_proto_todo2_proto protoreflect.FileDescriptor

const file_proto_todo2_proto_rawDesc = "" +
	"\n" +
	"\x11proto/todo2.proto\x12\vexarp.todo2\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x06\n" +
	"\tTodo2Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x10 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12)\n" +
	"\x10long_description\x18\x03 \x01(\tR\x0flongDescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12=\n" +
	"\vstatus_enum\x18\x11 \x01(\x0e2\x1c.exarp.todo2.Todo2TaskStatusR\n" +
	"statusEnum\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12C\n" +
	"\rpriority_enum\x18\x12 \x01(\x0e2\x1e.exarp.todo2.Todo2TaskPriorityR\fpriorityEnum\x12#\n" +
	"\rpriority_rank\x18\x13 \x01(\x05R\fpriorityRank\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\"\n" +
	"\fdependencies\x18\a \x03(\tR\fdependencies\x12\x1c\n" +
	"\tcompleted\x18\b \x01(\bR\tcompleted\x12@\n" +
	"\bmetadata\x18\t \x03(\v2$.exarp.todo2.Todo2Task.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"project_id\x18\f \x01(\tR\tprojectId\x12\x1f\n" +
	"\vassigned_to\x18\r \x01(\tR\n" +
	"assignedTo\x12\x12\n" +
	"\x04host\x18\x0e \x01(\tR\x04host\x12\x14\n" +
	"\x05agent\x18\x0f \x01(\tR\x05agent\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\n" +
	"Todo2State\x12,\n" +
	"\x05todos\x18\x01 \x03(\v2\x16.exarp.todo2.Todo2TaskR\x05todos\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x129\n" +
	"\n" +
	"last_saved\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tlastSaved*\xed\x01\n" +
	"\x0fTodo2TaskStatus\x12!\n" +
	"\x1dTODO2_TASK_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TODO2_TASK_STATUS_TODO\x10\x01\x12!\n" +
	"\x1dTODO2_TASK_STATUS_IN_PROGRESS\x10\x02\x12\x1c\n" +
	"\x18TODO2_TASK_STATUS_REVIEW\x10\x03\x12\x1a\n" +
	"\x16TODO2_TASK_STATUS_DONE\x10\x04\x12\x1d\n" +
	"\x19TODO2_TASK_STATUS_BLOCKED\x10\x05\x12\x1f\n" +
	"\x1bTODO2_TASK_STATUS_CANCELLED\x10\x06*\xb5\x01\n" +
	"\x11Todo2TaskPriority\x12#\n" +
	"\x1fTODO2_TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TODO2_TASK_PRIORITY_LOW\x10\x01\x12\x1e\n" +
	"\x1aTODO2_TASK_PRIORITY_MEDIUM\x10\x02\x12\x1c\n" +
	"\x18TODO2_TASK_PRIORITY_HIGH\x10\x03\x12 \n" +
	"\x1cTODO2_TASK_PRIORITY_CRITICAL\x10\x04B$Z\"github.com/davidl71/exarp-go/protob\x06proto3"

var (
	file_proto_todo2_proto_rawDescOnce sync.Once
	file_proto_todo2_proto_rawDescData []byte
)

func file_proto_todo2_proto_rawDescGZIP() []byte {
	file_proto_todo2_proto_rawDescOnce.Do(func() {
		file_proto_todo2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_todo2_proto_rawDesc), len(file_proto_todo2_proto_rawDesc)))
	})
	return file_proto_todo2_proto_rawDescData
}

var file_proto_todo2_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_todo2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_todo2_proto_goTypes = []any{
	(Todo2TaskStatus)(0),          // 0: exarp.todo2.Todo2TaskStatus
	(Todo2TaskPriority)(0),        // 1: exarp.todo2.Todo2TaskPriority
	(*Todo2Task)(nil),             // 2: exarp.todo2.Todo2Task
	(*Todo2State)(nil),            // 3: exarp.todo2.Todo2State
	nil,                           // 4: exarp.todo2.Todo2Task.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_todo2_proto_depIdxs = []int32{
	0, // 0: exarp.todo2.Todo2Task.status_enum:type_name -> exarp.todo2.Todo2TaskStatus
	1, // 1: exarp.todo2.Todo2Task.priority_enum:type_name -> exarp.todo2.Todo2TaskPriority
	4, // 2: exarp.todo2.Todo2Task.metadata:type_name -> exarp.todo2.Todo2Task.MetadataEntry
	5, // 3: exarp.todo2.Todo2Task.created_at:type_name -> google.protobuf.Timestamp
	5, // 4: exarp.todo2.Todo2Task.updated_at:type_name -> google.protobuf.Timestamp
	2, // 5: exarp.todo2.Todo2State.todos:type_name -> exarp.todo2.Todo2Task
	5, // 6: exarp.todo2.Todo2State.last_saved:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_todo2_proto_init() }
func file_proto_todo2_proto_init() {
	if File_proto_todo2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_todo2_proto_rawDesc), len(file_proto_todo2_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_todo2_proto_goTypes,
		DependencyIndexes: file_proto_todo2_proto_depIdxs,
		EnumInfos:         file_proto_todo2_proto_enumTypes,
		MessageInfos:      file_proto_todo2_proto_msgTypes,
	}.Build()
	File_proto_todo2_proto = out.File
	file_proto_todo2_proto_goTypes = nil
	file_proto_todo2_proto_depIdxs = nil
}
