// automation_execution_cockpit.go — Automation action for execution cockpit job.
package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/davidl71/exarp-go/internal/database"
	"github.com/davidl71/exarp-go/internal/framework"
	"github.com/davidl71/exarp-go/proto"
	"github.com/spf13/cast"
)

// handleAutomationExecutionCockpit runs an idempotent “execution cockpit” job intended for scheduling.
// It reuses the existing automation_runs overlap guard (beginAutomationRun/finishAutomationRun).
//
// Outputs:
// - Always returns a structured JSON summary.
// - Optionally writes a markdown or json file to output_path (default: docs/EXECUTION_COCKPIT.md).
func handleAutomationExecutionCockpit(ctx context.Context, params map[string]interface{}) ([]framework.TextContent, error) {
	start := time.Now()

	scheduleLabel := strings.TrimSpace(cast.ToString(params["schedule_label"]))
	if guard, skipResult, err := beginAutomationRun(ctx, "execution_cockpit", scheduleLabel); err == nil {
		if skipResult != nil {
			skipResponse := map[string]interface{}{
				"status":  "skipped",
				"results": skipResult,
			}
			resultJSON, _ := json.Marshal(skipResponse)
			resp := &proto.AutomationResponse{Action: "execution_cockpit", ResultJson: string(resultJSON)}
			return framework.FormatResult(AutomationResponseToMap(resp), "")
		}
		defer finishAutomationRun(ctx, guard, "success", "")
	} else {
		// If run tracking fails, still proceed (best-effort), but include warning in output.
		if params == nil {
			params = map[string]interface{}{}
		}
		params["run_tracking_warning"] = err.Error()
	}

	projectRoot, err := FindProjectRoot()
	if err != nil {
		return nil, fmt.Errorf("execution_cockpit: %w", err)
	}

	// Ensure database is initialized for report/task access (tests call tool handlers directly).
	if _, dbErr := database.GetDB(); dbErr != nil {
		if initErr := database.Init(projectRoot); initErr != nil {
			return nil, fmt.Errorf("execution_cockpit: init database: %w", initErr)
		}
	}

	// Build execution briefing JSON via the existing report tool implementation.
	briefing, err := handleReportExecutionBriefing(ctx, map[string]interface{}{
		"limit":         25,
		"output_format": "json",
		"compact":       true,
	})
	if err != nil {
		return nil, fmt.Errorf("execution_cockpit: execution_briefing: %w", err)
	}
	briefingJSON := ""
	if len(briefing) > 0 {
		briefingJSON = strings.TrimSpace(briefing[0].Text)
	}

	// Optionally write a persisted artifact for humans/other tooling.
	outputPath := strings.TrimSpace(cast.ToString(params["output_path"]))
	if outputPath == "" {
		outputPath = filepath.Join(projectRoot, "docs", "EXECUTION_COCKPIT.md")
	}
	outputFormat := strings.TrimSpace(cast.ToString(params["output_format"]))
	if outputFormat == "" {
		outputFormat = "markdown"
	}

	wroteFile := false
	if outputPath != "" {
		if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
			return nil, fmt.Errorf("execution_cockpit: create output dir: %w", err)
		}

		var data []byte
		switch strings.ToLower(outputFormat) {
		case "json":
			data = []byte(briefingJSON)
		default:
			data = []byte(renderExecutionCockpitMarkdown(projectRoot, briefingJSON))
		}
		if err := os.WriteFile(outputPath, data, 0o644); err != nil {
			return nil, fmt.Errorf("execution_cockpit: write output: %w", err)
		}
		wroteFile = true
	}

	result := map[string]interface{}{
		"status":        "success",
		"action":        "execution_cockpit",
		"project_root":  projectRoot,
		"duration_sec":  time.Since(start).Seconds(),
		"output_path":   outputPath,
		"output_format": outputFormat,
		"wrote_file":    wroteFile,
		"briefing_json": briefingJSON,
		"generated_at":  time.Now().Format(time.RFC3339),
	}
	if warn, ok := params["run_tracking_warning"]; ok && warn != nil {
		result["run_tracking_warning"] = warn
	}

	resultJSON, _ := json.Marshal(result)
	resp := &proto.AutomationResponse{Action: "execution_cockpit", ResultJson: string(resultJSON)}
	return framework.FormatResult(AutomationResponseToMap(resp), "")
}

func renderExecutionCockpitMarkdown(projectRoot, briefingJSON string) string {
	// Keep this intentionally simple: embed the JSON payload for downstream parsing.
	// The UX-first "task review" surface can render this file and link it back to tasks/runs.
	var b strings.Builder
	b.WriteString("# Execution cockpit\n\n")
	b.WriteString("Generated by `automation action=execution_cockpit`.\n\n")
	b.WriteString("## Payload (JSON)\n\n")
	b.WriteString("```json\n")
	b.WriteString(briefingJSON)
	b.WriteString("\n```\n")
	return b.String()
}
