#!/usr/bin/env bash
# Generate docs/VENDOR_LICENSES.md from vendor/modules.txt and vendor/*/LICENSE*.
# Run from repo root: ./scripts/vendor_licenses.sh
# Used by: make vendor-licenses

set -e
REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || echo .)}"
cd "$REPO_ROOT"
OUT="${1:-docs/VENDOR_LICENSES.md}"
MODULES_TXT="vendor/modules.txt"

# Infer license name from first few lines of a LICENSE file
license_infer() {
  local f="$1"
  if [ ! -f "$f" ]; then echo "—"; return; fi
  local head
  head=$(head -5 "$f" 2>/dev/null | tr '\n' ' ')
  if echo "$head" | grep -qi "MIT License"; then echo "MIT"; return; fi
  if echo "$head" | grep -qi "Apache License"; then echo "Apache-2.0"; return; fi
  if echo "$head" | grep -qi "Mozilla Public"; then echo "MPL-2.0"; return; fi
  if echo "$head" | grep -qi "BSD 3-Clause\|BSD-3\|Redistribution and use"; then echo "BSD-3"; return; fi
  if echo "$head" | grep -qi "BSD-2\|two.clause"; then echo "BSD-2"; return; fi
  if echo "$head" | grep -qi "Creative Commons\|CC0"; then echo "CC0"; return; fi
  if echo "$head" | grep -qi "GNU General Public"; then echo "GPL"; return; fi
  # default: show filename so human can check
  echo "See $(basename "$f")"
}

# Find first LICENSE* in vendor path (module path may contain /v2 etc.)
find_license() {
  local vdir="vendor/$1"
  [ -d "$vdir" ] || return 1
  for f in "$vdir"/LICENSE "$vdir"/LICENSE.md "$vdir"/LICENSE.txt "$vdir"/LICENSE-MIT; do
    [ -f "$f" ] && echo "$f" && return 0
  done
  # modernc.org/sqlite has SQLITE-LICENSE
  for f in "$vdir"/LICENSE* "$vdir"/SQLITE-LICENSE; do
    [ -f "$f" ] && echo "$f" && return 0
  done
  return 1
}

{
  echo '<!-- Generated by scripts/vendor_licenses.sh - do not edit by hand -->'
  echo ''
  echo '# Vendor packages – credits and licenses'
  echo ''
  echo 'exarp-go vendors Go dependencies in `vendor/`. The original **exarp** project maintained a third-party notices / credits file; this document continues that practice and lists each vendored package with its license for attribution and compliance.'
  echo ''
  echo '**How to regenerate:** run `make vendor-licenses` (or `./scripts/vendor_licenses.sh` from repo root).'
  echo ''
  echo 'For duplication checks and improvement ideas (e.g. spf13/cast, rate limiter), see [VENDOR_USAGE_AND_IMPROVEMENTS.md](VENDOR_USAGE_AND_IMPROVEMENTS.md).'
  echo ''
  echo '| Package | Version | License | License file |'
  echo '|---------|---------|---------|--------------|'
} > "$OUT"

awk '/^# [^ ]+ / { mod=$2; ver=$3; if (mod != "" && mod != "##" && !seen[mod]++) print mod, ver }' "$MODULES_TXT" | while read -r mod ver; do
  lic_file=""
  lic_name="—"
  if lic_file=$(find_license "$mod" 2>/dev/null); then
    lic_name=$(license_infer "$lic_file")
  fi
  # Relative path for table
  rel="${lic_file#$REPO_ROOT/}"
  [ -z "$rel" ] && rel="$lic_file"
  [ -n "$rel" ] || rel="—"
  printf '| %s | %s | %s | %s |\n' "$mod" "$ver" "$lic_name" "$rel"
done >> "$OUT"

echo ''
echo '---'
echo '*Generated by `make vendor-licenses`.*'
echo '' >> "$OUT"

echo "Wrote $OUT"
