# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge.proto
# Protobuf Python Version: 6.33.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    3,
    '',
    'bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62ridge.proto\x12\x0c\x65xarp.bridge\"{\n\x0bToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\x12\x14\n\x0cproject_root\x18\x03 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x05\x12\x12\n\nrequest_id\x18\x05 \x01(\t\"\x80\x01\n\x0cToolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x04 \x01(\x03\x12\x12\n\nrequest_id\x18\x05 \x01(\t\x12\x11\n\texit_code\x18\x06 \x01(\x05\"H\n\x0fResourceRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x14\n\x0cproject_root\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"j\n\x10ResourceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x11\n\tmime_type\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\tB$Z\"github.com/davidl71/exarp-go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"github.com/davidl71/exarp-go/proto'
  _globals['_TOOLREQUEST']._serialized_start=30
  _globals['_TOOLREQUEST']._serialized_end=153
  _globals['_TOOLRESPONSE']._serialized_start=156
  _globals['_TOOLRESPONSE']._serialized_end=284
  _globals['_RESOURCEREQUEST']._serialized_start=286
  _globals['_RESOURCEREQUEST']._serialized_end=358
  _globals['_RESOURCERESPONSE']._serialized_start=360
  _globals['_RESOURCERESPONSE']._serialized_end=466
# @@protoc_insertion_point(module_scope)
